### ISSUE TITLE
Short reads in target areas. Is it expected? 

### ISSUE THREAD

**Issue by Tine-dk** [LooseLab/readfish#116]
Hi,

I have made 4 runs with ReadFish, and there are consistently smaller reads inside the target areas. 
I do see an increase in depth in the target areas and long reads. But I can't explain the short reads. 
Are shorts reads in the target regions expected with ReadFish?
![FMR1](https://user-images.githubusercontent.com/67691621/99510698-aa55b700-2987-11eb-9d6e-e0ffd0842ade.PNG)
![HTT](https://user-images.githubusercontent.com/67691621/99510744-b6da0f80-2987-11eb-8062-0bef29fabb25.PNG)
![FMR1](https://user-images.githubusercontent.com/67691621/99523464-64085400-2997-11eb-84ed-47d6b7b4bb6d.PNG)
![HTT](https://user-images.githubusercontent.com/67691621/99523471-666aae00-2997-11eb-8956-65ee51920ba2.PNG)

Best, Tine

**Comment by Tine-dk** [comment]
Hi, any information on this?
I am defending a master thesis in two weeks and could get a question regarding this. 

Thanks in advance :)

**Comment by mattloose** [comment]
Hi,

So - this is one of those questions that is impossible for us to answer as it entirely depends on your library. If your library contains short molecules and they are on target then they will be sequenced.

Hope this helps.

Matt
