### ISSUE TITLE
Cannot connect to Guppy basecall server

### ISSUE THREAD

**Issue by StevenVerbruggen** [LooseLab/readfish#120]
Hi developpers,

I am testing the readme test steps of your Readfish package on a configuration test flow cell on a GridIon machine connected to a Linux desktop. Unblocking results look really similar to the histogram shown in your readme, although I need to use the fast basecalling in the minKNOW GUI and the parameters `--action-throttle 0.4 --throttle 0.4` for the unblock-all program.
So far so good.

For testing the basecalling and mapping, I adapted your human chromosome selection toml file for my purpose as follows:
```
[caller_settings]
config_name = "dna_r9.4.1_450bps_fast"
host = "127.0.0.1"
port = 5555

[conditions]
reference = "/data/genomes/igenomes/Homo_sapiens/Ensembl/GRCh38/Sequence/Index/hsa_genome.mmi"

[conditions.0]
name = "select_chr_21_22"
control = false
min_chunks = 0
max_chunks = inf
targets = ["chr21", "chr22"]
single_on = "stop_receiving"
multi_on = "stop_receiving"
single_off = "unblock"
multi_off = "unblock"
no_seq = "proceed"
no_map = "proceed"
```

In htop I saw following basecalling server running: `/usr/bin/guppy_basecall_server --config dna_r9.4.1_450bps_fast.cfg --port 5555 --log_path /var/log/minknow/guppy --ipc_threads 2 --max_queued_reads 5000 --num_callers 3 -x cuda:all`
So I suppose the caller settings in my toml match the running basecall server.

Validation of my toml file did not give any error or warning.

Running: `readfish targets --device X1 --experiment-name "RU Test basecall and map" --toml human_chr_selection.toml --log-file ru_test.log --action-throttle 0.4 --throttle 0.4` however resulted in following error message:
```
  File "/data/software/readfish/bin/readfish", line 10, in <module>
    sys.exit(main())
  File "/data/software/readfish/lib/python3.7/site-packages/ru/cli.py", line 33, in main
    args.func(parser, args)
  File "/data/software/readfish/lib/python3.7/site-packages/ru/ru_gen.py", line 452, in run
    caller_kwargs=caller_kwargs,
  File "/data/software/readfish/lib/python3.7/site-packages/ru/ru_gen.py", line 145, in simple_analysis
    caller = Caller(**caller_kwargs)
  File "/data/software/readfish/lib/python3.7/site-packages/ru/basecall.py", line 49, in __init__
    self.connect()
  File "/data/software/readfish/lib/python3.7/site-packages/pyguppyclient/client.py", line 81, in connect
    self.pcl_client.get_error_message())
ConnectionError: Connect with 'dna_r9.4.1_450bps_fast' failed: Could not get details from server (invalid response).
```

Seems the right basecaller server is not accessible after all?

I use following versions of the tools:
Readfish 0.0.5a1
MinKNOW has version 20.10.6 with following subpackages:
minKNOW core gridion 4.1.2
bream4-gridion 6.1.4
configuration customer gridion 4.1.15
gridion mooneye 1.3.5
guppy for gridion 4.2.3

**Comment by alexomics** [comment]
What version of `pyguppyclientlib` do you have installed?

You should be able to find this by running `pip list | grep guppy` in the readfish virtual environment.

**Comment by StevenVerbruggen** [comment]
I get these versions:
```
ont-pyguppy-client-lib 4.0.11   
pyguppyclient          0.0.7a1 
```
However, maybe linked to this, we also manually updated guppy to the latest version for other projects, so searching for this version gives:
```
$ guppy_basecall_server --version
: Guppy Basecall Service Software, (C) Oxford Nanopore Technologies, Limited. Version 4.2.3+f90bd04, client-server API version 3.2.0
```

**Comment by alexomics** [comment]
Yep, the version of `ont-pyguppy-client-lib` needs to be close to the `guppy_basecall_server` version. 

running:
```bash
pip install --upgrade ont-pyguppy-client-lib==4.2.3
```

should update the package to the required version.

**Comment by StevenVerbruggen** [comment]
Hi Alex,

Thanks for the tip. I did this but got following message:

'pyguppyclient 0.0.7a1 requires ont-pyguppy-client-lib==4.0.11, but you have ont-pyguppy-client-lib 4.2.3 which is incompatible.'

**Comment by alexomics** [comment]
Are you installing from PyPI? The package is a bit outdated there. Instead could you try installing from the [`dev`](/looselab/readfish/tree/dev) branch using the [instructions here](https://github.com/LooseLab/readfish/tree/dev#installation-development-version)?

**Comment by StevenVerbruggen** [comment]
I ran this:
```
# Install our ReadFish Software
pip install git+https://github.com/nanoporetech/read_until_api@v3.0.0
pip install git+https://github.com/LooseLab/readfish@dev

# Install ont_pyguppy_client_lib that matches your guppy server version. E.G.
pip install ont_pyguppy_client_lib==4.2.3
```
So readfish is surely from the dev branch. Is there a dev branch specifically for the ont_pyguppy_client_lib too? Still got the pyguppyclient 0.0.7a1 warning with this last line though.

**Comment by alexomics** [comment]
You need to remove:
```
pip uninstall pyguppyclient
```

**Comment by StevenVerbruggen** [comment]
Hi Alex,
Thanks a lot! Targets command seems to run now. As such, I can use Guppy 4.2.3 server at default port 5555. I applied it on a sequencing run for 15 minutes, selecting for chrs 21 and 22 as you did in the manual and then took the summary. There is unblocking observable based on the bases per chromosome, but the read lengths do not seem to be significantly larger for these chromosomes.

```
contig  number      sum  min    max    std  mean  median    N50
  chr1    1419  2585895  203  52429   4566  1822    1021   1831
 chr10     784  1449773  224  51409   4555  1849     834   2050
 chr11     822  1377118  214  41893   4214  1675     774   1835
 chr12     901  1635097  255  47574   4069  1815    1197   1782
 chr13     431   741471  220  43769   3523  1720    1401   1737
 chr14     563  1011422  239  50973   4000  1796    1094   1896
 chr15     705  1099101  270  48406   3700  1559     892   1704
 chr16     579   988248  223  43381   2676  1707    1611   1721
 chr17     454   688731  271  43374   2981  1517     884   1795
 chr18     388   798690  324  43465   4642  2058    1381   2032
 chr19     480   799995  265  50235   3639  1667     966   1758
  chr2    1329  2773550  222  52651   4912  2087    1428   2051
 chr20     370   873086  202  47397   5955  2360     980  11538
 chr21      98   305457  372  25305   4092  3117    1628   5635
 chr22      86   378333  276  47279   7814  4399    1724  12559
  chr3    1252  1891844  200  52580   3786  1511     760   1767
  chr4    1231  2158575  206  52692   3887  1754    1195   1790
  chr5    1209  2067142  251  49611   3954  1710    1029   1801
  chr6     970  1581574  216  41490   3294  1630    1339   1802
  chr7     731  1547518  277  53544   5196  2117    1100   2468
  chr8     839  1387708  183  49667   4084  1654     885   1782
  chr9     796  1605594  220  49060   4466  2017    1434   2006
 chrMT     146   218386  275  19578   2203  1496     925   1785
  chrX     883  1536295  209  55457   3712  1740    1182   1793
  chrY       8    43367  845  31511  10549  5421    1787  31511
```

![Screenshot from 2020-12-11 17-04-16](https://user-images.githubusercontent.com/15814435/101926299-48c5e880-3bd3-11eb-9b42-41bb177504bd.png)
![Screenshot from 2020-12-11 17-05-00](https://user-images.githubusercontent.com/15814435/101926303-49f71580-3bd3-11eb-9705-6190eddf3f45.png)
![Screenshot from 2020-12-11 17-04-34](https://user-images.githubusercontent.com/15814435/101926305-49f71580-3bd3-11eb-8d25-e54780be8c84.png)

Furthermore, unblocking times seem good but not as optimal as in your example.
<img width="383" alt="Screenshot 2020-12-11 at 17 00 10" src="https://user-images.githubusercontent.com/15814435/101925899-b9203a00-3bd2-11eb-8762-565cafbcc41b.png">

I already tweaked some parameters:
- I use the 'fast' mode of the basecall server
- max chunks is set to 8 instead of 'inf'
- I use --throttle 4

This was the command:
```
readfish targets --device X1 --experiment-name "RU Test basecall and map" --toml human_chr_selection.toml --log-file ru_test.log --throttle 0.4
```

And this is the toml file:
```
[caller_settings]
config_name = "dna_r9.4.1_450bps_fast"
host = "127.0.0.1"
port = 5555

[conditions]
reference = "/data/genomes/igenomes/Homo_sapiens/Ensembl/GRCh38/Sequence/Index/genome_readfish.mmi"

[conditions.0]
name = "select_chr_21_22"
control = false
min_chunks = 0
max_chunks = 8
targets = ["chr21", "chr22"]
single_on = "stop_receiving"
multi_on = "stop_receiving"
single_off = "unblock"
multi_off = "unblock"
no_seq = "proceed"
no_map = "proceed"
```
[ru_test.log](https://github.com/LooseLab/readfish/files/5680276/ru_test.log)


Any ideas, parameters or ways to improve this?
