### ISSUE TITLE
Pore occupancy

### ISSUE THREAD

**Issue by daniel007s** [LooseLab/readfish#122]
Hi, I wonder if you could advise on pore occupancy whilst using Readfish. I've prepared a HMW library from genomic DNA using SQK-LSK109, with approx. fragment size of 30kb. I loaded ~3.5ug of adapted DNA. When I started the run, pore occupancy in the sequencing state was high (~70%), which I inferred to mean that I'd loaded enough material. However, on initiating Readfish around 60 seconds after the mux scan, the sequencing pores has dropped to ~ 25%. Having read a previous post similar to this query, I note that the example duty time plot shows around 50% of pores sequencing at the start of a ReadFish run. Is there anything, practical or computational, that you could recommend to try to increase the output? Thanks.

**Comment by mattloose** [comment]
Hi Daniel, So - long libraries are always more difficult to get occupancy up on. We would tend to overload the library to get occupancy up but it can be hard to do this. I would advise loading about 1.5 times the normal molarity of a run when running readfish to see if that increases occupancy.

We did spend a bit of time working with longer read libraries and they are challenging to get high occupancy on particularly with readfish.

SO - in short - tyr overloading and good luck!

**Comment by daniel007s** [comment]
Thanks Matt - appreciate the swift response. Will give the overloading a try and keep everything crossed!
