### ISSUE TITLE
mapping time longer than 0.4 seconds

### ISSUE THREAD

**Issue by WaxRain** [LooseLab/readfish#123]
HI I'm trying to use readfish with the hope to complete target sequense.. I'm running into a few issues.

when I do as described in Testing expected results from a selection experiment part, I got times longer then 2 seconds
readfish targets --device  MN32XXX  --experiment-name "rf"  --toml human_chr_selection.toml  --log-file ru_test.log
due to CPU,break_reads_after_seconds = 1.0

the summary results show no evidence that target contigs are longer than other contigs.
![2020-12-28 17-17-33屏幕截图](https://user-images.githubusercontent.com/24712670/103251290-475a3580-49b3-11eb-9f77-e76645503df4.png)

![image](https://user-images.githubusercontent.com/24712670/103251508-e121e280-49b3-11eb-92b6-25915b5db6fe.png)

Any advice on how to approach this?

**Comment by DrOllyGomez** [comment]
Hiya. 
I've seen the same thing regarding high times.

I read issue number #81:   https://github.com/LooseLab/readfish/issues/81
The provided example .toml file on this githib site uses the guppy setting.....

[caller_settings]
config_name = "dna_r9.4.1_450bps_hac"

.....ie the 'hac' bit means to use high-accuracy basecalling, not fast basecalling, i believe.

In issue #81, mattloose  said: "OK - my standard response would be to try the fast mode"

I changed the setting in my .toml to...
config_name = "dna_r9.4.1_450bps_fast"
... and that has certainly had a major effect in bringing the numbers down to below 0.5.....
(and can see the purple 'Data Service Unblock Mux Change" fraction of the histogram go sky high :) )

Very new to all this, hope this was the right suggestion to make. I may try the further suggestion in #81 next...
Please someone shout me down if this is not the right way to go.

Mike
