### ISSUE TITLE
Installing 0.0.5a2 on GridION and avoiding bricking the system

### ISSUE THREAD

**Issue by DrOllyGomez** [LooseLab/readfish#124]
Hi folks
Massively keen to give readfish a go on our new GridION. (which has version 4 of things...)
I note the comment and link to the pre -release version of readfish on PyPI. Went there to have a look, seems to require >=python3.7
Factory-shipped system python(s) are 2.7 and 3.5.1
I appreciate the stuff about using venvs for walling off dependencies, but not sure how to get a 3.7 environment sorted out that doesnt cause problems for eg MINKNOW etc.
Could you please make some comments about your preferred way of both:
1)keeping everything running smoothly for the ONT systems 
2)getting readfish installed to sit next to it with its requirements: which route to go down to get a sandboxed python3.7 or above without clobbering.
Many thanks indeed. Excited at prospect of being rid of mitochondrial ribosomal RNAs 1 and 2 !! :)
Mike

**Comment by alexomics** [comment]
Hi Mike, 

I'd recommend using (mini)conda to get things started:

```bash
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /data/miniconda.sh
bash /data/miniconda.sh -p /data/.miniconda
```
This will download and begin the miniconda installation, using `/data/.miniconda` as the install path as the home directory on GridION isn't the largest.

Follow the prompts on the installer screens. You should accept the default settings.  
To make the changes take effect, close and then re-open your terminal window.

To get a readfish environment started with miniconda you can make a file called `readfish_env.yml` using this:

```yaml
name: readfish
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - pip:
    - read-until==3.0.0
    - ont-pyguppy-client-lib==4.2.3
    - git+https://github.com/LooseLab/readfish@dev
```
the guppy version may not have an exact version match, you can find your system guppy version by running:

```bash
guppy_basecall_server --version 
```

To create the environment run: 
```bash
conda env create -f readfish_env.yml
conda activate readfish
```

Then, if you've got a [readfish TOML](https://github.com/LooseLab/readfish/blob/dev/TOML.md) file already setup you can run:

```bash
readfish validate /path/to/experiment.toml
```

to test the setup.

**Comment by DrOllyGomez** [comment]
many thanks indeed - and for such a swift reply!! will try this tomorrow and report.

**Comment by alexomics** [comment]
Let me know if you hit any snags, we're quite keen to make installation easy!

**Comment by DrOllyGomez** [comment]
Pretty smooth going! 
One hiccup: the system needs to have git installed before starting.   

[I knew how to get this going, but it probably be part of the install notes]. I deleted the partly-finished conda environment and re-issued the install again and it got to the end fine. Thanks v much!!

The validation command suggested works fine, I'll go through the simulation/playback with the bulkfile suggested in the markdown notes next, with the unblock, and then get fishing next week!

It took me a little while to find in the GUI where the 'reload scripts' was: wondered if you'd considered a screenshot might be a help in the docs?
 
Couple of minor questions:
1) presumably the 'scripts' referred to in that 'reload scripts' are system-wide (and not properties of individual Xn stations on the GridION? In other words, does each Xn have its own set of scripts or are they shared?)
2) is it of paramount importance to get the file-permissions (user&group) on the various toml files absolutely right? wondered if I was editing the textfile as one user, and MINKNOW was reading it as a different user, whether that might cause it to hang/crash/whatever?
3) and just as a conceptual/understanding type thing, I believe that the adaptive sequencing scripts you've written work because MINKNOW is periodically polling and re-reading these toml files. is that right? and if so, how often does it do it?

All in all : many many thanks for the install notes. Top notch.
Best
Mike

**Comment by DrOllyGomez** [comment]
Ok, not so hot on the running of the playback files, seem to get this unusual error message:

![Screenshot from 2021-01-15 16-48-49](https://user-images.githubusercontent.com/50023481/104755433-52062000-5752-11eb-8c09-01df0dab77b1.png)

...and cant get underway.

here's the version info etc:
minknow core: 4.1.2
ontbream4 gridion 6.1.4
ontconfig customer 4.1.15
ont-gridion-mooneye 1.3.5
ont-guppy-for-gridion 4.2.3

**Comment by mattloose** [comment]
That's not one I've seen before. It's also a MinkNOW error not a readfish error.

Have you manually set the location here to playback? I tend to leave the output folder as the default (/data/) and then go from there. The output is then automatically named as Experiment Name. Can you double check that behaviour?

**Comment by DrOllyGomez** [comment]
Cough... er... that's working fine now, thanks v much!
Must have been the curse of friday afternoon or something.
