### ISSUE TITLE
readfish states

### ISSUE THREAD

**Issue by 12032345** [LooseLab/readfish#129]
Hi，

With the bulk file you provided, I want to eject all the human's chromosome. 
The system message shows "ReadFish States - accepted 0.00% of 20525 total reads. Unblocked 11426 reads."

Why the number of unblocked reads is not equal to the total reads?

The toml file I used:

[caller_settings]
config_name = "dna_r9.4.1_450bps_hac"
host = "127.0.0.1"
port = 5555

[conditions]
reference = "/path/to/reference.mmi"

[conditions.0]
name = "human_deplete"
control = false
min_chunks = 0
max_chunks = 12
targets = "/home/grid/target"
single_on = "unblock"
multi_on = "unblock"
single_off = "proceed"
multi_off = "proceed"
no_seq = "proceed"
no_map = "proceed"

target file: all the chromosome name in human genome reference

Looking forward to your reply, thank you very much！

Sophie

**Comment by mattloose** [comment]
Hi Sophie,

You are correct - this does sound odd. My first guess is that you are basecalling too slowly. This would mean that you would miss some reads - I would suggest you try the FAST model for basecalling and also look on our wiki here - https://github.com/LooseLab/readfish/wiki/Basecalling-Settings

If this doesn't help - please reply and include the read until logs telling us how fast your basecalling is. (i.e the screen ouput). You might want to save a chunk log as well.

Matt

**Comment by 12032345** [comment]
Hi Matt,

Thanks for your reply!
I changed to FAST mode but things didn't seem to improve. 
As you can see from the log file, it is not a basecalling speed problem:

![image](https://user-images.githubusercontent.com/70840449/105811547-c315c500-5fe7-11eb-8fd0-df6f552ca0f0.png)

I also saved a chunk log. What puzzles me is that in theory all reads should be able to map to targets. But as you can see from the chunk log, only half of them are mapped and successfully unblocked, so why?

![image](https://user-images.githubusercontent.com/70840449/105812215-b6de3780-5fe8-11eb-9fca-196d379f1a69.png)

sophie

**Comment by mattloose** [comment]
Hi Sophie

https://github.com/LooseLab/readfish/wiki/Basecalling-Settings#guppy-4011-fast-model-30-minutes-no-adapter-scaling

you will need to use the no adapter scaling option for playback. Sorry - I keep forgetting about this. When playing back a file the playback breaks the assumption that each read begins with an adapter. So try this one. 

It should then work. 

Matt

**Comment by 12032345** [comment]
Hi Matt,

I have used the no adapter scaling option, and the reafish states has become normal.
The thing is, I want to deplete the human genome from a mixture of human and pathogenic samples. So I did a playback with the bulk file you provided. 

The toml file I used:

[caller_settings]
config_name = "dna_r9.4.1_450bps_fast"
host = "127.0.0.1"
port = 5555

[conditions]
reference = "/path/to/reference.mmi"

[conditions.0]
name = "human_deplete"
control = false
min_chunks = 0
max_chunks = inf
targets = "/home/grid/target"
single_on = "unblock"
multi_on = "unblock"
single_off = "stop_receiving"
multi_off = "stop_receiving"
no_seq = "proceed"
no_map = "proceed"

target file: all the chromosome name in human genome reference
With this toml file I want to unblock all the human DNA. 

The basecalling speed is normal.
But in the chunk_log I found that only half of the reads were unblocked, and the other half of the reads decision was proceed. 
Does proceed mean to sequence that reads? 
![image](https://user-images.githubusercontent.com/70840449/105854840-5b30a000-6022-11eb-978b-b25dc1669b75.png)

I expected the result would similar to unblock_all, but now the result is obviously not. 
Will this affect my real readuntil experiment? can I use this toml file to achieve my experimental purpose?
By the way, in a real readuntil experiment, should I use no adapter scaling option?

Hope to be able to get your help, very grateful!

**Comment by mattloose** [comment]
Hi,

You need to look more carefully at the chunk log. You will find (probably) that you see each read more than once - so you grab some data from it and it doesn't map, then you grab a bit more and it maps and is rejected. Check how many unique read ids are in your file - it won't be the same as the sum of the two numbers you show here.

For a real read until experiment I would use the no adapter scaling option. In our hands it gives better performance. But we haven't extensively tested this.

Matt

**Comment by 12032345** [comment]
Okay, I get it, thank you very much！
