### ISSUE TITLE
run error - flow cell not checked

### ISSUE THREAD

**Issue by Huanle** [LooseLab/readfish#130]
Hi readfish developers,

Thanks heaps for developing this nice software. 
This issue might not be directly related to readfish. But i wonder if some users could  have also run into the same issue.

So i posted it here.

I had a trial with readfish, it worked. Then i tried it again and just wanted to make sure with gpu basecalling, it works even better. 

But I came across this issue shown in the picture i attached here. 

The system messages say: `Stopping protocol due to internal error. All data will be saved`.

I am using minknow gui: 4.0.21 and minknow core 4.0.5.

![Screenshot from 2021-01-25 13-01-57](https://user-images.githubusercontent.com/909201/105835792-9902d980-5fcc-11eb-9979-5881a9a812f5.png)

Hopefully some of you can help sort it out.
Thanks a lot in advance.

**Comment by mattloose** [comment]
Hi,

So this is something you might be better asking nanopore themselves - these issues do sometimes happen and there are log files that might tell you what is happening - but this most likely an issue on the minknow side and not readfish.

Look in 
```/var/log/minknow/```
for more help.
