### ISSUE TITLE
config file for enrichment and depletion

### ISSUE THREAD

**Issue by Huanle** [LooseLab/readfish#135]
Hi There,

Thanks a lot for developing readfish! 

Do you have example toml configuration file for all experiments that you did in table2 of your published work 

The  [example](https://github.com/LooseLab/readfish/blob/master/examples/human_chr_selection.toml) run in the readme seems to be enriching the sequencing of reads mapped to chr21 and chr22, right?
If the experiment was to avoid sequencing these two chromosomes, how should the toml file be set up?  changing 
```
single_on = "stop_receiving"
multi_on = "stop_receiving"
single_off = "unblock"
multi_off = "unblock"
no_seq = "proceed"
no_map = "proceed"
```
to

```
single_on = "unblock"
multi_on = "unblock"
single_off = "stop_receiving"
multi_off = "stop_receiving"
no_seq = "proceed"
no_map = "proceed"
```
?

Another question is whether it is legal to include only the target reference chromosomes in the reference sequence file?

Thanks very much again!

**Comment by dawnmy** [comment]
No answer to this question? I set it to the latter one for depletion but the output are all human reads.

**Comment by dawnmy** [comment]
Thank you so much for the answer. Yes, I tested on a real sample which has >90% human contamination. Your explanation fits what I observed: the human reads are short (<600bp). What would be the best config settings to get rid of the human reads as much as possible.

**Comment by dawnmy** [comment]
I finished my adaptive sequencing run on real clinical sample with readfish today. My purpose was to deplete human sequences. After comparing with the run without using adaptive sequencing powered by readfish, I found the adaptive sequencing run has even more human reads. In half of the samples the non human reads are much shorter than human reads. Everything seems to be the opposite of what I expected. The setting is:
```
[conditions]
reference = "/data/ref_data/GRCh38_p14.mmi"

[conditions.0]
name = "deplete_human_genome"
control = false
min_chunks = 0
max_chunks = inf
targets = ["NC_000001.11","NC_000002.12","NC_000003.12","NC_000004.12","NC_000005.10","NC_000006.12",
    "NC_000007.14","NC_000023.11","NC_000008.11","NC_000009.12","NC_000011.10","NC_000010.11",
    "NC_000012.12","NC_000013.11","NC_000014.9","NC_000015.10","NC_000016.10","NC_000017.11",
    "NC_000018.10","NC_000020.11","NC_000019.10","NC_000024.10","NC_000022.11","NC_000021.9"]

single_on = "unblock"
multi_on = "unblock"
single_off = "stop_receiving"
multi_off = "stop_receiving"

no_seq = "proceed"
no_map = "proceed"

```
Did I set anything wrong?

**Comment by mattloose** [comment]
This is a complex experiment. You say you have more human reads - but you should have more reads - but they should be shorter than the human reads in the control data set. Your non human reads should only be unblocked if they map to human for some reason (which they could of course). You would need to compare the non human readlengths in your control versus the adaptive sampling experiment to see if they have been rejected or are just shorter than the human material.

So - in summary - you should get more reads in total on an adaptive sampling run than a non adaptive run. If you are just looking at read count and not considering read length you will not be interpreting your data correctly. Hope that helps. I can't see anything immediately wrong with your toml file.
