### ISSUE TITLE
low speed of mapping

### ISSUE THREAD

**Issue by sams898** [LooseLab/readfish#136]
Hello,
I am running the readfish test basecalling and mapping, and am getting mapping speeds that are sometimes greater than 0.4s. It says that I may have performance issues if this is the case; is there anything I can do to fix this? I attached a screenshot where the speed of mapping was being reported for the test set. 

Thank you!
Sam
![readfish_speed_mapping](https://user-images.githubusercontent.com/71793751/108609204-629a5d80-73c4-11eb-946e-f9e794d7798e.png)

**Comment by mattloose** [comment]
Hi

You might find this helpful - we suggest you play with the basecaller settings as shown here - https://github.com/LooseLab/readfish/wiki/Basecalling-Settings

good luck!

**Comment by sams898** [comment]
Great, I will try changing the basecaller settings to fast, thank you!
