### ISSUE TITLE
Mac Big Sur installation

### ISSUE THREAD

**Issue by chrlesw** [LooseLab/readfish#138]
I just don't seem able to install Read Fish on my macbook pro (big sur). I follow the instructions and each time  get an error building deepnano-blitz. Could anyone who has succeeded in getting everything up and running on a Mac help ? 
Thanks, Charles

**Comment by alexomics** [comment]
What instructions are you following/could you outline the steps you've taken? I've just realised the pre-built wheels have expired so I'm re-building them right now.

**Comment by chrlesw** [comment]
Thanks for the quick response Alex, 

I started from https://looselab.github.io/2020/12/02/readfish-cpu.html
which took me to
https://github.com/alexomics/deepnano-blitz/actions/runs/324655081
where I opened the "code" tab and followed the instructions in the README.md file. 
I also installed the mkl-static package (conda install -c intel mkl-static) after creating and activating the conda deepnanoblitz environment steps. 
Regards, Charles

**Comment by chrlesw** [comment]
The python setup.py install runs happiliy for a while and then fails with build errors. I can re-rn the whole thing if you want more details.
charles

**Comment by alexomics** [comment]
Ah! Sorry, on the second link there is supposed to be an artefact that you could download and install with, but it has expired. I've re-built the installers and they are here https://github.com/alexomics/deepnano-blitz/actions/runs/610693635

![image](https://user-images.githubusercontent.com/30386655/109507462-afea8f00-7a96-11eb-8d0a-c985a5b15f14.png)

If you download that zip file you can select the right installer for your system.

**Comment by chrlesw** [comment]
Thanks Alex, it installed with no problem. I'm doing the rest of the Read Fish installation and if this goes well, then the real work will begin :
Regards, Charles

**Comment by chrlesw** [comment]
Alex,
sorry to bother you again, but I'll be very grateful if you can help again.  I've blocked installing 
pip install git+https://github.com/nanoporetech/read_until_api@v3.0.0

It insistes on replacing numpy-1.20.1 with version numpy-1.17.4 , but  h5py required numpy>=1.19.3. I've tried hunting down and removing numpy 1.17 with both conda and pip and reinstalling the 1.20 to no avail. 
Here's the end of the terminal output from the pip install git+https://github.com/nanoporetech/read_until_api@v3.0.0

...
Successfully built read-until
Installing collected packages: six, protobuf, numpy, grpcio, minknow-api, read-until
  Attempting uninstall: numpy
    Found existing installation: numpy 1.20.1
    Uninstalling numpy-1.20.1:
      Successfully uninstalled numpy-1.20.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
h5py 3.1.0 requires numpy>=1.19.3; python_version >= "3.9", but you have numpy 1.17.4 which is incompatible.
Successfully installed grpcio-1.36.0 minknow-api-4.1.5 numpy-1.17.4 protobuf-3.15.3 read-until-3.0.0 six-1.15.0

**Comment by alexomics** [comment]
What python version are you using?

**Comment by chrlesw** [comment]
3.9.2

**Comment by alexomics** [comment]
Yeah, I've just taken a look at h5py. They require numpy>=1.19.3 for python3.9. Could you try this install using python3.7?

```
# Minimum supported versions of Numpy & Cython depend on the Python version
NUMPY_MIN_VERSIONS = [
    # Numpy    Python
    ('1.14.5', "=='3.7'"),
    ('1.17.5', "=='3.8'"),
    ('1.19.3', ">='3.9'"),
]
```
from https://github.com/h5py/h5py/blob/21a4acffde3da03a9fcbe3eab211c58b88eac56c/setup.py#L27-L33

**Comment by chrlesw** [comment]
trying it

**Comment by chrlesw** [comment]
it worked!  I've gone through the readfish install up to the pyguppy client install, I need to read around before dealing with this :)
Very appreciative of your help, thanks again, 
Charles

Here're the details in case they help someone:
conda create -n deepnano37 python=3.7
conda activate deepnano37
pip install /Users/me/Desktop/artifact/deepnano2-0.1-cp37-cp37m-macosx_10_15_x86_64.whl
pip install git+https://github.com/nanoporetech/read_until_api@v3.0.0
pip install git+https://github.com/LooseLab/readfish@caller_refactor

**Comment by alexomics** [comment]
Fantastic! Let us know if you run into any other issues/have questions.
