### ISSUE TITLE
Bulk playback FAST5 file

### ISSUE THREAD

**Issue by visanuwan** [LooseLab/readfish#139]
Hi Matt,

I did get the Readfish working as described in the README with Minknow 20.10.3.
Just out of curiosity, there were more than 60% inactive pores when I was trying to replay the bulk fast5 provided in the README (see the screenshot below). Is this normal? Could you please confirm it?

![Screen Shot 2021-03-11 at 9 59 50 AM](https://user-images.githubusercontent.com/1764254/110817689-25521e80-8252-11eb-98b9-e603de6d88cf.png)

**Comment by mattloose** [comment]
Hi,

I'd have to re run the bulk locally to test this but this observation wouldn't surprise me. I will check.

**Comment by susanruimingao** [comment]
Hi,

I have also seen similar higher rates of inactivate pores.

I have a different question with this bulk playback FAST5 file:
When I tried the bulk fast5 in the README, it worked as expected. However, when I used my own bulk fast5 (with similar size as the FAST5 file in README), it kept showing "Not enough data to render".

Not sure if  there are any specific features for the README FAST5, I just cat my fast5 files in one run, showing "PMA_run2.fast5" in the screenshot.

Thanks for your kind guidance.
Susan
![Not enough data](https://user-images.githubusercontent.com/41761481/113913383-46068900-97aa-11eb-94c6-8e049bfff896.png)
![dataset size](https://user-images.githubusercontent.com/41761481/113913408-4d2d9700-97aa-11eb-9354-1cf8f36b44d4.png)

**Comment by alexomics** [comment]
@susanruimingao it seems like your run only lasted 5 seconds in that instance. Were  there any messages about the bulk FAST5 file in the MinKNOW interface? Are you able to run playback normally?

**Comment by susanruimingao** [comment]
Yes, I can run playback normally with the FAST5 data provided in README.

When I changed to my own FAST5, the run stopped immediately with error. No, I did not see any messages about my bulk FAST5 file in the MinKNOW interface.

I just noticed one weird issue, my own fast5 file is shrinking to "79,862,525" from "29,404,821,585". So did my other prepared FAST5 files. 

How did you prepare the FAST5 file provided in the README please? Thanks  
![shrinked dataset](https://user-images.githubusercontent.com/41761481/113915638-03927b80-97ad-11eb-9b76-e83104b07a63.png)

**Comment by alexomics** [comment]
The bulk FAST5 file we provide was recorded from a minion run in 2017. 

How did you produce your bulk FAST5 file? There’s an output option in minknow to create this file

**Comment by susanruimingao** [comment]
I have used a 2019 run with MinION IT, and we kept all the raw data output files in a Seagate hard disk. The output files were listed in the screenshot.  

Under the folder "fast5_pass", I have copied both folders of "barcode01" and "barcode02" to my work station terminal path. Then firstly cat all the fast5 files together in the barcode01 folder as dataset1, then barcode02 folder as datasets 02.

Finally, to cat both dataset01 and dataset02 as "PMA_run2.fast5". 
![Steps for Fast5 file](https://user-images.githubusercontent.com/41761481/113922263-1741e000-97b5-11eb-9c89-0319f8384085.png)

**Comment by alexomics** [comment]
A bulk FAST5 file must be recorded at the time of sequencing, you cannot produce a file that will work with playback in the way that you have. There are instructions on the [ONT community protocols](https://community.nanoporetech.com/protocols/experiment-companion-minknow/v/mke_1013_v1_revbm_11apr2016/starting-a-sequencing-run-on-minion), specifically step 10 - advanced user options - that detail how to collect a bulk FAST5 file

**Comment by susanruimingao** [comment]
Thanks so much for your kind help to figure out my problem. Alex. New ONT knowledge learned.
