### ISSUE TITLE
Playback of fast5 files on MacOS Big Sur

### ISSUE THREAD

**Issue by dithiii** [LooseLab/readfish#141]
I am trying to test out the deepnanoblitz caller on Readfish with CPU support. Looks like everything is installed happily, however I cannot get Minknow to playback a fast5 successfully (with or without readfish). It gives an error that it cannot read the HDF5 file. I have installed hdf5 via "brew install hdf5" and pip appears to have h5py installed.

What am I missing?

**Comment by alexomics** [comment]
Hi dithiii, sorry for the slow reply.

Are you using the bulk FAST5 file that we have supplied? Have you got ONT's VBZ compression software installed? https://github.com/nanoporetech/vbz_compression
