### ISSUE TITLE
Module Not Found Error

### ISSUE THREAD

**Issue by elisaguo** [LooseLab/readfish#143]
Hi all,

I'm trying to get readfish set up in our lab. 
I've installed: 
- MinKNOW 21.02.1 (MinKNOW core 4.2.5)
- Guppy 4.5.2
- read_until_api v3
- readfish 0.0.6

When I try to run it, it gives an error: **ModuleNotFoundError: No module named 'read_until.read_cache'.** I'm not sure how to fix this. I don't have much experience with command line, so any advice is appreciated! Please let me know if you need any additional information.

Thanks in advance,

Elisa

**Comment by elisaguo** [comment]
Hi Alex,

Thank you for the prompt reply!
Please see the screenshot attached.
![image](https://user-images.githubusercontent.com/81648550/113160101-29e37480-920b-11eb-859b-8bbf1a11e3dc.png)

**Comment by alexomics** [comment]
Your `read-until` version is not correct (2.1.0). If you run:

```bash
pip install --upgrade read-until
```
and then check with:
```bash
pip list | grep "read-until"
```

which should output:
```
read-until             3.0.0
```

**Comment by elisaguo** [comment]
It's working now! Turns out I also needed to install PyGuppy. Thanks again for your help!
