### ISSUE TITLE
meaning of *start_analysis* and *end_analysis* in chunk_log file

### ISSUE THREAD

**Issue by lingolingolin** [LooseLab/readfish#146]
Hi there,

What does analysis, e.g. *start_analysis* and *end_analysis* refer to in the *chunk_log* file?
Does  it include basecalling, reads mapping and making decisions ?

Thanks a lot.

**Comment by alexomics** [comment]
This is the alignment analysis time for that read chunk. `start_time` is when the alignment was first seen, `end_time` is the time (just after) the decision is made and communicated to MinKNOW. At the moment we only log the complete cycle time to the terminal in the format: `10R/0.12345s`, this can be captured using the `--log-file` flag when running readfish.
