### ISSUE TITLE
Strange playback results

### ISSUE THREAD

**Issue by JensUweUlrich** [LooseLab/readfish#149]
Hi,

I have a question that is related to the testing of basecalling an mapping with readfish. I used the provided bulk fast5 file from your example and tried to enrich for chromosome 20 using the following toml configuration file

[caller_settings]
config_name = "dna_r9.4.1_450bps_fast.cfg"
host = "127.0.0.1"
port = 5556

[conditions]
reference = "chm13.mmi"

[conditions.0]
name = "target_chr20"
control = false
min_chunks = 0
max_chunks = 4
targets = ["chr20"]
single_on = "stop_receiving"
multi_on = "stop_receiving"
single_off = "unblock"
multi_off = "unblock"
no_seq = "proceed"
no_map = "proceed"

The basecall server was running on my GPU and reads were unblocked as expected. I ran the playback for 30 minutes and MinKNOW reported an estimated N50 for unblocked reads of 507 bases. Reads were also basecalled on the fly. No the strange part: When running `readfish summary`, I get the following results:

contig  number      sum  min     max    std   mean  median     N50
  chr1     255  4141675  222  335172  35699  16242    4702   69574
 chr10     122  2521855  296  266359  39982  20671    5078   74437
 chr11     147  2211878  280  309230  36475  15047    3693   79547
 chr12     160  2253240  223  113909  23087  14083    4558   47498
 chr13      67   993923  228  182676  30574  14835    2568   58478
 chr14     144  2682821  258  238804  38004  18631    3048  103585
 chr15     118  2148794  250  176996  33661  18210    5958   78504
 chr16      80  1537956  237  192687  34452  19224    4637   64049
 chr17      77  1570468  357  356009  50485  20396    5301  120914
 chr18      59  1096667  383  122990  26707  18588    7241   45462
 chr19      96  1859153  280  168258  35389  19366    5950   93671
  chr2     262  3995000  223  231492  32486  15248    4580   76241
 chr20      56  1634910  225  172704  41106  29195    9220   77877
 chr21      40  1110569  388  244474  57540  27764    6201  173438
 chr22      34   330004  445   69195  14645   9706    3634   31652
  chr3     199  3330467  198  247579  37482  16736    5002   99939
  chr4     192  3815358  214  241444  39589  19872    5382   76238
  chr5     218  4457045  214  320784  41907  20445    5362   90951
  chr6     192  2284670  242  151117  22369  11899    5079   45480
  chr7     170  2886579  207  254014  35711  16980    2543   70706
  chr8     155  2516083  213  274309  39663  16233    5146   60350
  chr9     163  2984923  247  249482  36559  18312    4926   73934
  chrM      26   204801  284   16559   6294   7877    6680   14060
  chrX     155  2945093  237  191603  37198  19001    6058   76243

Thus it seems like MinKNOW does not care about unblock messages for playback runs in the final outputs. Have you recognized similar results?

Thanks
Jens

**Comment by mattloose** [comment]
Hi,

This doesn't make sense - if MinKNOW is reporting unblocked reads with an N50 of 500 bases you should see that in your data. Readfish summary should reflect that in the output shown here. 

So firstly there is a conflict between MinKNOW reporting and final data - that is not something we would expect to see - the se normally match up.

Which version of Guppy are you using?

You might want to have a look here at this wiki which shows some of the effects of changing basecalling parameters with different guppy versions - in particular the modifications we make for adapter scaling.

https://github.com/LooseLab/readfish/wiki/Basecalling-Settings

Can you provide a bit more detail on your setup with Guppy and which GPU etc.

Thanks

Matt

**Comment by JensUweUlrich** [comment]
I recognized this same behavior for Guppy 4.5.4 and Guppy 5.0.7. I am using Nvidia GeForce 1050 and started the basecall server with `guppy_basecall_server -c dna_r9.4.1_450bps_fast.cfg --log_path /home/jens/data/readfish/guppy_logs/ --port 5556 -x auto --gpu_runners_per_device 3 --num_callers 2 --chunk_size 1000`.

Thanks for pointing at the adapter scaling issue. I think I will try to a playback run without adapter scaling and get back to you later with the results.

Thanks also for your quick reply! 
Jens

**Comment by mattloose** [comment]
OK - currently we haven't tested extensively on Guppy 5.0.7.

I would suggest dropping the adapter scaling as you say and seeing how it performs. If you are running live basecalling on MinKNOW at the same time I would switch that off and just use the 1050 for the read until basecalling component. 

I'm still puzzled as to why MinKNOW was reporting such a short N50 for unblocked reads - when you do your next playback run can you add in some screenshots of the read length histogram in MinKNOW?

**Comment by JensUweUlrich** [comment]
OK - I repeated the 30 minute run with adapter scaling disabled in `dna_r9.4.1_450bps_fast.cfg`. It all looks fine in MinKNOW.
![Screenshot from 2021-06-04 14-06-07](https://user-images.githubusercontent.com/46562264/120806841-9d756b00-c547-11eb-9e58-cb7ef9a296b2.png)

This time I disabled basecalling in MinKNOW like I always do, and basecalled with guppy_basecaller after the run finished. using the following call `guppy_basecaller -c /opt/ont/minknow/guppy/data/dna_r9.4.1_450bps_fast.cfg -m /opt/ont/minknow/guppy/data/template_r9.4.1_450bps_fast.jsn -x auto --gpu_runners_per_device 3 --num_callers 2 --chunk_size 1500 -i fast5/ -s fastq`

But it doesn't seem to have any impact on the results of `readfish summary`:

chr1     284  5506138  226  433701  40967  19388    5016   72150
 chr10     154  3537749  255  288962  43798  22972    4697   91933
 chr11     173  3152846  282  306882  38659  18225    4059   79047
 chr12     170  2986354  297  205979  31065  17567    5358   66305
 chr13      92  1896308  221  215673  41959  20612    2889  101066
 chr14     129  2967482  222  176193  39079  23004    7432   94523
 chr15     162  3524815  233  189367  36171  21758    7735   74268
 chr16      93  1862851  233  239370  34323  20031    5569   62817
 chr17      97  2168643  199  400580  51869  22357    5153  108162
 chr18      90  2465313  287  403978  53653  27392    7790   78007
 chr19     109  2086762  298  233732  41207  19145    4797   96069
  chr2     295  5347665  218  299803  38127  18128    4793   80859
 chr20      55  1682135  134  170423  40650  30584   15059   76982
 chr21      40  1455576  262  383196  73257  36389    9023  189758
 chr22      44   494150  237   77187  16247  11231    5064   23141
  chr3     236  5045951  242  317773  44433  21381    4983   84737
  chr4     223  5682564  209  307929  47276  25482    6736   91832
  chr5     224  5295013  253  369284  46818  23638    5815  108037
  chr6     217  3505416  235  189122  30395  16154    5026   73876
  chr7     179  4093046  200  438202  50249  22866    4474  103121
  chr8     194  3288162  187  368995  43343  16949    4162   74840
  chr9     184  4189937  219  359047  49329  22771    5772   84952
  chrM      30   190355  269   16401   6059   6345    4094   13278
  chrX     193  3674042  215  319050  44932  19036    3523  124961

I also wonder why there is no `as_model_file` parameter in the standalone guppy config files. I only saw this parameter in the minknow/guppy/data/dna_r9.4.1_450bps_fast.cfg` file. Is there a parameter in for the guppy_basecaller that turns off adapter_scaling?

Thanks
Jens

**Comment by mattloose** [comment]
OK - I'm going to point you to here:

https://github.com/LooseLab/readfish/wiki/Testing

And in particular the images for the unblocks (admittedly in an older version of MinKNOW):
![image](https://user-images.githubusercontent.com/8202484/120808829-5e441b80-c541-11eb-979a-efbad6babde7.png)

In this image we are looking at bases rather than numbers of reads - but it's possible to estimate what is happening here - from the screenshot you show from MinKNOW it is unblocking reads - but only a tiny number.

For Chromosome 1 you are only seeing 284 reads - in our playbacks we get 10 times that number of reads. My suspicion is that your setup is too slow. The unblocks that get sent to MinKNOW quickly enough do work but on average most reads are being missed.

When readfish is running you should see reporting on the speed of mapping:
```
2020-02-24 16:45:35,677 ru.ru_gen 7R/0.03526s
2020-02-24 16:45:35,865 ru.ru_gen 3R/0.02302s
2020-02-24 16:45:35,965 ru.ru_gen 4R/0.02249s
```

what sort of figures are you seeing whilst it is running?

**Comment by JensUweUlrich** [comment]
This could explain the issue. My number look like this:

> [2021-06-04 13:33:53.264117] [0x00007f3d92ffd700] [info]    Connected to server as ''. Connection id: 747683e1-9882-4a86-bea4-7955a1840f58
2021-06-04 13:33:53,378 ru.ru_gen 1R/0.11386s
2021-06-04 13:33:53,832 ru.ru_gen 18R/0.16714s
2021-06-04 13:33:54,812 ru.ru_gen 93R/0.34605s
2021-06-04 13:33:55,434 ru.ru_gen 17R/0.16666s
2021-06-04 13:33:55,868 ru.ru_gen 42R/0.20048s
2021-06-04 13:33:56,714 ru.ru_gen 41R/0.24587s
2021-06-04 13:33:57,458 ru.ru_gen 23R/0.18901s

So probably you are right with my setup being too slow. Is there anything I can change in the setup other than using fast basecalling without adapter scaling? For example the number of gpu_runners or the number of callers?

Thanks again!
Jens

**Comment by mattloose** [comment]
You might want to look here to see if there is useful information you can use - https://github.com/sirselim/jetson_nanopore_sequencing/blob/main/xav_adaptive_sampling.md

The smallest GPU we have managed to work with is the 1080 - but we've not pushed the limit much beyond that.

**Comment by JensUweUlrich** [comment]
OK - Thanks for your help. I will have a look and see if I can manage to get it running.

Best wishes
Jens
