### ISSUE TITLE
cannot find reference & target fields in the toml file

### ISSUE THREAD

**Issue by YingziZhang-github** [LooseLab/readfish#160]
Hi there,
I sucessfully tested unblock response and would like to test basecalling and mapping. I made a local copy of the example TOML file by using the command `curl -O https://github.com/LooseLab/readfish/blob/master/examples/human_chr_selection.toml`
But for the following

> Modify the reference field in the file to be the full path to a minimap2 index of the human genome.
> Modify the targets fields for each condition to reflect the naming convention used in your index. This is the sequence name only, up to but not including any whitespace. e.g. >chr1 human chromosome 1 would become chr1. If these names do not match, then target matching will fail.
I couldn't find the reference or the targets fields in the file. Would you please tell me their location? Thank you very much!

**Comment by alexomics** [comment]
Your cURL command will download an HTML page, not the file. You should use the raw link:

```bash
curl -O https://raw.githubusercontent.com/LooseLab/readfish/master/examples/human_chr_selection.toml
```
Then in this file lines 7 and 14 are the reference and targets fields respectively. You can see more details about the TOML configuration here: https://github.com/LooseLab/readfish/blob/master/TOML.md
