### ISSUE TITLE
Sample data

### ISSUE THREAD

**Issue by woodoo46** [LooseLab/readfish#161]
Hi there,

It might be mentioned somewhere, but I am just curious what kind of data is inside the example file "http://s3.amazonaws.com/nanopore-human-wgs/bulkfile/PLSP57501_20170308_FNFAF14035_MN16458_sequencing_run_NOTT_Hum_wh1rs2_60428.fast5" ? For example, how many reads do we expect to see, how much coverage on human genome and is it whole genome sequencing or a targeted sequencing? 

Thanks.

George

**Comment by alexomics** [comment]
This bulk FAST5 file is from a run for [Nanopore sequencing and assembly of a human genome with ultra-long reads][1], it was un-targeted whole genome sequencing. From [the data page for that project][2] (flow cell FAF14035) I can see that run generated 101,222 reads, but I think this bulk FAST5 file captured roughly 13,000 reads. I'm not sure what duration it captures but MinKNOW will repeat playback/simulation in a loop until the set run duration has elapsed. Coverage will be repeated only over regions seen in the file.

 [1]: https://www.nature.com/articles/nbt.4060
 [2]: https://github.com/nanopore-wgs-consortium/NA12878/blob/master/Genome.md
