### ISSUE TITLE
R10/Q20+

### ISSUE THREAD

**Issue by daniel007s** [LooseLab/readfish#163]
Hi, I was wondering if there's any technical/hard-coded reason why an R10 flow cell with Q20+ prep wouldn't be compatible with readfish? I have yet to try but would like to. 

Many thanks,

Daniel

**Comment by nathanconr** [comment]
Anything on this? So far all I have seen are examples of R9 compatibility but I would like to try this with R10.
Thanks,
Nathan

**Comment by mattloose** [comment]
So - this is perhaps one for @alexomics to comment on - we did see some issues on R10 with how we were implementing readfish but we believe these now to be resolved. I would suggest if you are just using a simple static panel to try ONT's built in adaptive sampling. If you want to do something more sophisticated (e.g barcodes with different panels etc) then you would need to use a specific branch to better handle the mux scans (this appears to be especially an issue with kit14).

**Comment by nathanconr** [comment]
Thank you for the quick answer! What I would like to do is have a single target panel on all barcodes (R10 flow cell with kit14 library). I guess the built in adaptive sampling would be the option of choice then.

**Comment by mattloose** [comment]
Yes - I'd try that. We would be interested in knowing how it performs...

**Comment by nathanconr** [comment]
I will keep you updated!
