### ISSUE TITLE
Unifying data yields across barcodes

### ISSUE THREAD

**Issue by Irsan88** [LooseLab/readfish#165]
I'd like to use the barcode-aware functionality to get uniform data yields across GridION runs. Is this functionality included in this repository already? I cannot find anything about it in the documentation.

**Comment by mattloose** [comment]
Hi, There is no automated way to do this at present. In our experience any automated approach we have tried is confounded by different read lengths across samples,  unexpected extreme outliers or very low coverage samples. There are other approaches one can try and we are looking at automating these in the future.

At present the most straightforward implementation is to switch off specific barcodes once you have acquired enough data for that specific sample. We are working on a tool that will do this and which should be available fairly soon - @alexomics illustrated this in his recent NCM talk.

One could implement an approach to automate normalisation of barcodes based on read counts etc but for now this is not something we have stable enough to provide to others.

**Comment by Irsan88** [comment]
Ok clear, I will wait until the that tool is available, for useful work by year team!
