### ISSUE TITLE
Which sequencing experiment generated the example Bulk Fast5 file?

### ISSUE THREAD

**Issue by Huanle** [LooseLab/readfish#166]
Hi readfish developers,

Can you tell me which sequencing experiment was performed to generate the fast5 file - [PLSP57501_20170308_FNFAF14035_MN16458_sequencing_run_NOTT_Hum_wh1rs2_60428.fast5](http://s3.amazonaws.com/nanopore-human-wgs/bulkfile/PLSP57501_20170308_FNFAF14035_MN16458_sequencing_run_NOTT_Hum_wh1rs2_60428.fast5)?  
In another word, what was sequenced？
Thanks a lot in advance!

**Comment by Huanle** [comment]
I think i found the answer [here](https://github.com/nanopore-wgs-consortium/NA12878/blob/master/Genome.md). But it would be nice to get the bulf fast5 files for NB4 cell line and the ZymoBIOMICS sequencing experiments. Can you please let me know if this is possible?

**Comment by mattloose** [comment]
Hi,
You are correct - the example bulk file is a sequencing run for NA12878. We provide that file as it did not itself have readfish run on it. We have a short bulk file available for ZymoBIOMICS which we might be able to make available if we can find an appropriate location to host it.

We will post a link here if we can.

**Comment by Huanle** [comment]
Hi @mattloose ,

Thanks a lot for your prompt reply.
I look forward to have a go with the ZymoBIOMICS data. 

Best,
