### ISSUE TITLE
Repeat Mac Big Sur installation

### ISSUE THREAD

**Issue by kuma0077** [LooseLab/readfish#168]
Alex,

Thanks for all of your documentation. I've got an updated request following from the previous issue: 
https://github.com/alexomics/deepnano-blitz/actions/runs/610693635

![image](https://user-images.githubusercontent.com/6118106/148102929-006b170c-1c2a-4a4e-9612-65a9e0fc784e.png)
The artifact has expired. Would you mind rerunning?

**Comment by alexomics** [comment]
The pre-built DeepNano-Blitz installers are all individually available for Ubuntu and MacOS [in the repo for our blog][7]

[7]: https://github.com/LooseLab/looselab.github.io/tree/master/static/
