### ISSUE TITLE
Computer specifications for use with MinION

### ISSUE THREAD

**Issue by Kav57** [LooseLab/readfish#169]
I am looking to buy a desktop/laptop to sequence using a MinION with readfish. I was wondering if you could advise on the minimum specifications required to run readfish realtime on a MinION device? Specifically is there a recommended minimum GPU specification? I am hoping to exclude the whole human genome, will this significantly increase the computational requirements?

**Comment by sirselim** [comment]
Hi @Kav57 - I'm not a readfish author or developer, but a big fan and user!

I wrote a bit of a document about selecting compute hardware, and specifically GPUs, for nanopore sequencing. If you are interested you can find it [here](https://hackmd.io/@Miles/B1U-cOMyu). The "spark notes below" try to summarise and give you a rough idea of what you should be looking for.

My recommendation would be:
 - a nice fast CPU, either AMD Ryzen7/9/Threadripper or Intel i7/i9 with 8+ cores
 - as much RAM as you can afford to put in, but at least 32GB minimum. If you are loading larger genomes (i.e. human) for things like adaptive sampling / readfish you need the RAM to hold the index.
 - GPU wise my go to recommendation is the Nvidia RTX3060 (some notes on that [here](https://hackmd.io/@Miles/BJc5hOkCu), and [here](https://hackmd.io/@Miles/BJc5hOkCu#UPDATE-more-GPUs-benchmarked)). The RTX3060 can easily keep up with live basecalling across each of the three models (FAST, HAC, SUP), and can even handle running multiple MinIONs if that's something you want to do.
 - one or more fast solid state hard drives, the NVMe PCIe drives are great and not too expensive

**Comment by Kav57** [comment]
Hi @sirselim, 

Thank you so much for this really informative response, you have been immensely helpful!
