### ISSUE TITLE
Dev branch - numpy versioning clash

### ISSUE THREAD

**Issue by lfearnley** [LooseLab/readfish#173]
Hi all!

Hopefully an easy one - I'm following the readfish dev branch install instructions in a conda environment, and I'm seeing a dependency issue when running the commands as specified:

`pip install git+https://github.com/nanoporetech/read_until_api@v3.0.0` installs and requires `numpy==1.17.4`.
`pip install git+https://github.com/LooseLab/readfish@dev` installs `numpy==1.22.2` and generates an incompatibility warning.

What's the cleanest way to resolve this? Will readfish run without issues on numpy 1.17.4/pandas 1.3.x?

**Comment by alexomics** [comment]
Sorry for the slow response. We don't have a hard requirement for numpy v1.22.2 on the dev branch. `pip` should, in this scenario, downgrade numpy to the pinned version used by the `read_until_api` but (as you mention) pandas is preventing this. 

I think the solution here is ensuring that pandas is set to `==1.3.?`. I have tried `1.3.1` and `1.3.3` which both install successfully. Please let me know how you get along with this

**Comment by lfearnley** [comment]
Hi @alexomics! Sorry about the delay - I've had a bit of a gap where I didn't want to touch the readfish install.

Setting pandas to 1.3 seems to be working ok in simulation, though I'm noticing a bit of a slowdown using guppy 6.0.6 relative to older versions of readfish - I think this might be a guppy issue though, as it's occuring on both a 2080Ti and an RTX A5000.
