### ISSUE TITLE
testing guppy_6 branch on Ubuntu 18.04 LTS with guppy server 5.1.12 fails with "stopped with error"

### ISSUE THREAD

**Issue by rainwala** [LooseLab/readfish#181]
Hello, I'm trying the simulation data test for the guppy_6 branch on Ubuntu 18.04 LTS with guppy server 5.1.12 

In step 6, I select "FLO-MIN106" as the flowcell type, followed by "LSK-109" as the kit type, then "sequencing_MIN106_DNA_playback.toml" as the script (which is the script I edited in steps 2 and 3). 

Then I started the sequencing run, and the GUI says "run state active" followed by getting to temperature. After it reaches temperature, it says "run state unknown", nothing happens for a few minutes, then it says "Stopped with error". Please see the attached screenshots. 
<img width="715" alt="Screenshot 2022-03-11 at 12 57 16" src="https://user-images.githubusercontent.com/14825266/157871023-726507d5-9f30-43ff-b7b8-75e3eb49038f.png">
<img width="721" alt="Screenshot 2022-03-11 at 12 57 40" src="https://user-images.githubusercontent.com/14825266/157871054-6168d58e-992b-4199-927c-8d3584d6fa97.png">

Here are the sections I edited in "sequencing_MIN106_DNA_playback.toml":
```
###############################
# Sequencing Feature Settings #
###############################

# basic_settings #
[custom_settings]
simulation = "/home/aawan/PLSP57501_20170308_FNFAF14035_MN16458_sequencing_run_NOTT_Hum_wh1rs2_60428.fast5"

```
```

[analysis_configuration.read_detection]
mode = "transition"
minimum_delta_mean = 80.0
look_back = 2
break_reads_after_events = 250
break_reads_after_seconds = 0.4
```

Do you know what might be happening or which logs to look at to find out more about the error MinKNOW is reporting? Thank you.

**Comment by rainwala** [comment]
Please help :)

**Comment by alexomics** [comment]
Sorry for the delay!

It looks like you're using the bulk FAST5 file that we provide, could you check that it is complete/not corrupted during download (have you been able to do simulations before)?

When I check the `sha256` hash I get:
```bash
$ sha256sum PLSP57501_20170308_FNFAF14035_MN16458_sequencing_run_NOTT_Hum_wh1rs2_60428.fast5
aab3710689782dca7c258185e4513fd238540665963441597b1db0343252250b  PLSP57501_20170308_FNFAF14035_MN16458_sequencing_run_NOTT_Hum_wh1rs2_60428.fast5
```

Then I would take a look at the MinKNOW logs, these should be in `/var/log/minknow`. You can `grep` for evidence of the bulk FAST5 being used like so:

```bash
grep -iR "_60428.fast5"
```

If you get any returned lines, check the file and see if there are any specific error messages.

**Comment by rainwala** [comment]
Hi again, thank you for this information. Here is the output of the sha256 hash:

```
$ sha256sum  ~/PLSP57501_20170308_FNFAF14035_MN16458_sequencing_run_NOTT_Hum_wh1rs2_60428.fast5 
aab3710689782dca7c258185e4513fd238540665963441597b1db0343252250b  PLSP57501_20170308_FNFAF14035_MN16458_sequencing_run_NOTT_Hum_wh1rs2_60428.fast5
```

**Comment by rainwala** [comment]
Here is the output of grepping the logs, which seems more informative:

```
$ grep -iR "_60428.fast5" /var/log/minknow/*/*
/var/log/minknow/MN18788/bream-0.txt:                     'simulation': '/home/aawan/PLSP57501_20170308_FNFAF14035_MN16458_sequencing_run_NOTT_Hum_wh1rs2_60428.fast5',
/var/log/minknow/MN18788/bream-1.txt:                     'simulation': '/media/HDD1/DATA/readfish/PLSP57501_20170308_FNFAF14035_MN16458_sequencing_run_NOTT_Hum_wh1rs2_60428.fast5',
/var/log/minknow/MN18788/bream-1.txt:[bream4.device_interfaces.devices.base_device:  31] - 2022-02-01 12:22:03,787 -     INFO - Failed to retrieve calibration data from /media/HDD1/DATA/readfish/PLSP57501_20170308_FNFAF14035_MN16458_sequencing_run_NOTT_Hum_wh1rs2_60428.fast5
/var/log/minknow/MN18788/control_server_log-0.txt:    source_hdf_file: /home/aawan/PLSP57501_20170308_FNFAF14035_MN16458_sequencing_run_NOTT_Hum_wh1rs2_60428.fast5
/var/log/minknow/MN18788/control_server_log-1.txt:    source_hdf_file: /media/HDD1/DATA/readfish/PLSP57501_20170308_FNFAF14035_MN16458_sequencing_run_NOTT_Hum_wh1rs2_60428.fast5
/var/log/minknow/MN18788/control_server_log-1.txt:           std::exception::what: boost::filesystem::status: Permission denied: "/media/HDD1/DATA/readfish/PLSP57501_20170308_FNFAF14035_MN16458_sequencing_run_NOTT_Hum_wh1rs2_60428.fast5"
/var/log/minknow/MN22761/bream-0.txt:                     'simulation': '/home/aawan/PLSP57501_20170308_FNFAF14035_MN16458_sequencing_run_NOTT_Hum_wh1rs2_60428.fast5',
/var/log/minknow/MN22761/bream-1.txt:                     'simulation': '/home/aawan/PLSP57501_20170308_FNFAF14035_MN16458_sequencing_run_NOTT_Hum_wh1rs2_60428.fast5',
/var/log/minknow/MN22761/bream-2.txt:                     'simulation': '/home/aawan/PLSP57501_20170308_FNFAF14035_MN16458_sequencing_run_NOTT_Hum_wh1rs2_60428.fast5',
/var/log/minknow/MN22761/control_server_log-0.txt:    source_hdf_file: /home/aawan/PLSP57501_20170308_FNFAF14035_MN16458_sequencing_run_NOTT_Hum_wh1rs2_60428.fast5
/var/log/minknow/MN22761/control_server_log-0.txt:    source_hdf_file: /home/aawan/PLSP57501_20170308_FNFAF14035_MN16458_sequencing_run_NOTT_Hum_wh1rs2_60428.fast5

```

**Comment by rainwala** [comment]
I would ignore all of those that have the fast5 file in "/media/HDD1/DATA/readfish/PLSP57501_20170308_FNFAF14035_MN16458_sequencing_run_NOTT_Hum_wh1rs2_60428.fast5"

It used to be on an external drive until Matt told me to put it on the main SSD drive. So all of those lines that refer to '/home/aawan/PLSP57501_20170308_FNFAF14035_MN16458_sequencing_run_NOTT_Hum_wh1rs2_60428.fast5' are relevant.

**Comment by alexomics** [comment]
Do you see any error messages in the file `/var/log/minknow/MN22761/control_server_log-0.txt`?

**Comment by rainwala** [comment]
```
$ grep ERROR /var/log/minknow/MN22761/control_server_log-0.txt
2022-03-11 12:19:23.309238   ERROR: observer_lagging_behind (state_control)
2022-03-11 12:19:36.843764   ERROR: guppy_client_failed_to_connect (basecalling)
2022-03-11 12:19:36.860163   ERROR: failed_to_preload_basecall_config (rpc)
2022-03-11 12:21:21.309706   ERROR: observer_lagging_behind (state_control)
2022-03-11 12:23:26.504065   ERROR: failed_to_finish_transition (state_control)
2022-03-11 12:23:26.742031   ERROR: stopping_protocol_due_to_internal_error (control)
2022-03-11 12:40:52.260606   ERROR: guppy_client_failed_to_connect (basecalling)
2022-03-11 12:40:52.261399   ERROR: failed_to_preload_basecall_config (rpc)
2022-03-11 12:43:39.638890   ERROR: observer_lagging_behind (state_control)
2022-03-11 12:45:37.639323   ERROR: observer_lagging_behind (state_control)
2022-03-11 12:45:54.282366   ERROR: guppy_client_failed_to_connect (basecalling)
2022-03-11 12:45:54.283115   ERROR: failed_to_preload_basecall_config (rpc)
2022-03-11 12:47:38.789924   ERROR: could_not_read_device_status (device)
2022-03-11 12:47:38.790286   ERROR: device_error (mgmt)
2022-03-11 12:47:42.812245   ERROR: failed_to_finish_transition (state_control)
```

**Comment by alexomics** [comment]
Are any of these at similar points in time to the simulation not starting? e.g `stopping_protocol_due_to_internal_error (control)` ?

**Comment by rainwala** [comment]
I can't remember, but we were trying to run the simulation via MinKNOW during the hour of 12pm to 1pm on the 11th.

**Comment by alexomics** [comment]
These lines that you have found via `grep` are typically just the first line, there is more information below them. Could you check to see if there are any more informative errors?

**Comment by rainwala** [comment]
[control_server_log-0.txt](https://github.com/LooseLab/readfish/files/8305614/control_server_log-0.txt)

**Comment by alexomics** [comment]
Just quickly looking I can see a few messages relating to flow cell connection. Were you using a CTC flow cell on the MinION when running playback? If you were can you successfully QC the device?

**Comment by rainwala** [comment]
I think we used a white test flow cell -- the placeholder one. I'll ask my laboratory scientist. As for the QC, we didn't run one as that wasn't asked for in the test instructions. However, is that something you would recommend?

**Comment by alexomics** [comment]
This maybe an issue with your guppy connection, can you run normally? i.e. put an old flow cell in and see if you can generate any data?

**Comment by rainwala** [comment]
We don't usually use the linux machine for ONT runs -- it's typically for data analysis. We usually use a windows machine in the lab. We only started trying with this to be able to use readfish .

We will try a regular run and report back. Thank you!

**Comment by rainwala** [comment]
Hi again, it now works fine! It was a problem from ONT as you and Matt had suspected. After upgrading the MinKNOW version from 21.11.7 to 21.11.8, the test run for unblocking all ran exactly as expected. We are now in the process of testing the selective sequencing.
