### ISSUE TITLE
readfish version

### ISSUE THREAD

**Issue by Flower9618** [LooseLab/readfish#183]
Hello, thanks for sharing this excellent tool.
My minKNOW version is 4.3.18, and Guppy version is 5.0.16. I was wondering which version of readfish I should install. 
By the way, "To configure a run for playback, you need to find and edit a sequencing TOML file. These are typically located in /opt/ont/minknow/conf/package/sequencing." means minKNOW and readfish should be installed in the same machine? 
Thank you very much!

**Comment by rainwala** [comment]
yes, they need to be installed on the same machine, which needs to be a linux machine.

**Comment by Flower9618** [comment]
Thank you very much for your reply. I thought the interaction between Readfish and minKNOW is based on IP and port, does 
 it mean they can be installed on the different machine? Sorry, maybe I did not understand it. And after these two tools have been installed, which one should run first?

**Comment by mattloose** [comment]
You can in principle run on two different machines.

However we do not recommend this.

The latency over the network may impact performance.

MinKNOW should always be running before readfish - readfish connects to MinKNOW to find information.
