### ISSUE TITLE
Recommended settings for short reads

### ISSUE THREAD

**Issue by 2tony2** [LooseLab/readfish#184]
Hi!

I was wondering if you have any recommendations when it comes to adaptive sequencing of short reads. Is there a practical limit you have run into? What can be done to reduce the size limit of reads which can be selected for through adaptive sequencing?

**Comment by mattloose** [comment]
Fundamentally, once your read length approaches the length of molecule that you need to look at to determine mapping there is no benefit to applying adaptive sampling. So the way to improve working with shorter reads is to be able to call and map shorter molecules.

Practical limits for a benefit at present are probably around the 1200 base mark. i.e you start to see some benefits once your molecule lenght is greater than 1200 bases.

**Comment by 2tony2** [comment]
Thank you Matt for your insights, this is definitely very helpful!
