### ISSUE TITLE
Advice on recording bulk playback file

### ISSUE THREAD

**Issue by samhorsfield96** [LooseLab/readfish#194]
Hi, 

I am planning on generating a bulk playback file with an upcoming MinION sequencing run so that I can run simulations from it with readfish. Do you have any advice on the best way to do this with MinKNOW to ensure the bulk file will be usable for these purposes?

Many thanks for your help,

Sam

**Comment by alexomics** [comment]
When setting up your run, on the `Output` options step select:

1. "Show advanced user options"
1. Set the "Output bulk file" option to on
1. Select the "Read table" and "Raw" options

I would only collect a bulk file for 1 hour or so as the files can get quite large. 

<img src="https://user-images.githubusercontent.com/30386655/165733973-4916360c-556e-4305-879f-94077695880f.png" width=550>
