### ISSUE TITLE
Reads not treated by adaptive sampling

### ISSUE THREAD

**Issue by lborcard** [LooseLab/readfish#197]
Dear All,

We are currently using adaptive sampling (enrichment protocol) on on minknow. We discovered that a portion of the read ( fastq_pass) are not part of the output report of the adaptive sampling (csv file) ? Does anyone know if it is a normal behaviour and could anyone provide an explanation as to why we observe that?

GridION
minKNOW 21.11.7

best regards

**Comment by xvazquezc** [comment]
It might be the same issue we are having with the standard adaptive. Check the ONT community post and comments if that's the same kind of thing
https://community.nanoporetech.com/posts/logging-of-reads-in-adapti

**Comment by mattloose** [comment]
Hi,

As you are not using readfish we are unable to provide support for you. 

As suggested you should check the ont community. 

Thanks.
