### ISSUE TITLE
Readfish on prom

### ISSUE THREAD

**Issue by hasindu2008** [LooseLab/readfish#199]
I tried the https://github.com/LooseLab/readfish/commit/23dd37117bce576b99caf097e7711dc87d30fa0a for readfish on the PromethION. The installation went smoothly, however, when I tried on an actual run (not a play back, an actual run with a previously used flowcell), the flowcell position went to an 'unknown' state.

What I did:
```
pip install git+https://github.com/LooseLab/readfish@23dd37117bce576b99caf097e7711dc87d30fa0a
pip install git+https://github.com/nanoporetech/read_until_api@v3.0.0
pip install ont-pyguppy-client-lib==6.1.5
```

TOML file:
```
[caller_settings]
config_name = "dna_r9.4.1_450bps_fast_prom"
host = "ipc:///tmp/.guppy"
port = 5555
barcode_kits = ["EXP-NBD104"]
align_ref = "/data/readfish/hg38noAlt.idx"

[conditions]
reference = "/data/readfish/hg38noAlt.idx"

[conditions.0]
name = "ReadFish_v6_gene_targets.collapsed.hg38"
control = false
min_chunks = 0
max_chunks = 16
targets = "ReadFish_v6_gene_targets.collapsed.hg38.txt"
single_on = "stop_receiving"
multi_on = "stop_receiving"
single_off = "unblock"
multi_off = "unblock"
no_seq = "proceed"
no_map = "proceed"
```

Command:
```
readfish targets --device 5F --experiment-name "ReadFish" --toml ReadFish.toml --cache-size 3000 --batch-size 3000 --channels 1 3000 --port 9502
```

The system log is here:
https://www.dropbox.com/s/wuuhr5i2cn2opxz/syslog.txt?dl=0

**Comment by hasindu2008** [comment]
Oh right. I launched it during the mux scan, my bad. I will reattempt it after the mux scan is completed - on Tuesday next week - as our PromethION is currently busy sequencing some other normal sequencing runs.

The 5F logs are here:
https://www.dropbox.com/sh/cvogti3vyg1kk2z/AADIxy9_MxICCbKjnCDzSWl-a?dl=0

**Comment by hasindu2008** [comment]
@alexomics 
This time I launched readfish after mux scan and it successfully communicated with read fish and printed the usual output.

Is it possible to disable the barcode-aware readfish and run normal readfish for the promethion? What change should I do to my toml?

**Comment by alexomics** [comment]
That should be just removing the `barcode_kits` from the TOML and running `readfish targets …`. The `align_ref` will still need to be set on the `caller_settings` table.

**Comment by hasindu2008** [comment]
Thanks for the quick response. Will soon give a try and let you know.

**Comment by hasindu2008** [comment]
![20220614_164520_HDR](https://user-images.githubusercontent.com/12987163/173511568-2d28dc4e-1cf5-4823-99c3-da954f976a9f.jpg)
Seems to be running. This is a check using a bad flowcell so the pore count is less.  Any idea what this red colour state in the end reason plot is?

**Comment by mattloose** [comment]
We are told the red is Minknow misclassifying those reads. We've seen it too and it isn't anything to be concerned about.

**Comment by hasindu2008** [comment]
Ok Thanks. What is the recommended amount of DNA to be loaded for R9.4.1 LSK110? Like for MinION flowcells is it recommended to be washed every 24 hours and reloaded?
