### ISSUE TITLE
Installing ReadFish on GridION

### ISSUE THREAD

**Issue by melkramer** [LooseLab/readfish#200]
Hello,

Could you please advise on the current method to install readfish?  I'm trying to install readfish for Guppy V6 as in Issue #170 but am getting this error:

# python3 -m venv readfish
# . readfish/bin/activate
(readfish) # pip3 install --upgrade pip
Collecting pip
  Using cached https://files.pythonhosted.org/packages/96/2f/caec18213f6a67852f6997fb0673ae08d2e93d1b81573edb93ba4ef06970/pip-22.1.2-py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 8.1.1
    Uninstalling pip-8.1.1:
      Successfully uninstalled pip-8.1.1
Successfully installed pip-22.1.2
(readfish) # pip install git+https://github.com/nanoporetech/read_until_api@v3.0.0
Traceback (most recent call last):
  File "/root/readfish/bin/pip", line 7, in <module>
    from pip._internal.cli.main import main
  File "/root/readfish/lib/python3.5/site-packages/pip/_internal/cli/main.py", line 57
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax

Thank you,
Melissa

**Comment by alexomics** [comment]
Hi Melissa, 

It looks like your `python3` executable is using Python v3.5 and that the upgraded version of `pip` is not compatible with python 3.5. 

For readfish we require a newer python version, ≥3.7. There are some [instructions for using conda to setup readfish in issue #124](https://github.com/LooseLab/readfish/issues/124#issuecomment-759599319).

Let me know if you are able to install readfish using the linked instructions. 

Alex

**Comment by melkramer** [comment]
Thank you, after updating to python 3.8 the conda setup is working!


Best,

Melissa


________________________________

**Comment by alexomics** [comment]
Fantastic! If you run into any other problems, please open a new issue.
