### ISSUE TITLE
Issues running test simulation on guppy 6 minKnow 5 branch

### ISSUE THREAD

**Issue by santiago-es** [LooseLab/readfish#205]
Hi all,

I'm fairly new to ONT sequencing and I'm attempting to use readfish for adaptive sampling. 

I installed readfish using the guppy 6 and minknow branch, and it seems to have done so correctly. 

When I attempt to run a simulation, I downloaded the bulk Fast5 playback file for testing readfish and changed the specified toml file as listed in the instructions, pointing the variable simulation to the fast5 playback file. I went into the MinKnow GUI and reloaded scripts and attempted to start sequencing for the simulation to begin but the sequencing run fails. I have our MinION MK1B plugged in with a configuration test cell inserted, and in the sequencing setup specified the flow cell corresponding to the edited toml file (MIN106, same as in the instructions). 

Any idea where I might be going wrong? Thanks in advance for your help!

**Comment by santiago-es** [comment]
BTW I am doing this on Ubuntu 22.04 and this is what my MinKnow GUI looks like when attempting to run a simulation

![image](https://user-images.githubusercontent.com/10642529/177617138-d24b9a9f-e6a0-45c4-b9ac-9e4d02bab4b8.png)

**Comment by santiago-es** [comment]
my toml file is pasted below, an edited version of sequencing_MIN106_DNA.toml 
`type = "protocol"

script = "sequencing/sequencing.py"

[meta]
exp_script_purpose = "sequencing_run"

[meta.protocol]
experiment_type = "sequencing"
flow_cells = ["FLO-MIN106", "FLO-FLG001"]
kits = [
    "SQK-16S024",
    "SQK-CAS109",
    "SQK-CS9109",
    "SQK-LSK109",
    "SQK-LSK109-XL",
    "SQK-LSK110",
    "SQK-LSK110-XL",
    "SQK-MLK110-96-XL",
    "SQK-MLK111-96-XL",
    "SQK-NBD110-24",
    "SQK-NBD110-96",
    "SQK-RAD004",
    "SQK-RAD111",
    "SQK-RBK004",
    "SQK-RBK110-96",
    "SQK-DCS109",
    "SQK-PCB109",
    "SQK-PCB110-24",
    "SQK-PCB111-24",
    "SQK-PCS109",
    "SQK-PCS110",
    "SQK-PCS111",
    "SQK-PRC109",
    "VSK-PTC001",
    "VSK-VSK002",
    "VSK-VSK003",
    "VSK-VSK004",
    "VSK-VMK002",
    "VSK-VMK003",
    "SQK-RAB204",
    "SQK-LRK001",
    "SQK-PBK004",
    "SQK-PSK004",
    "SQK-RPB004",
]

default_basecall_model = "dna_r9.4.1_450bps_fast.cfg"
available_basecall_models = ["dna_r9.4.1_450bps_fast.cfg",
                             "dna_r9.4.1_450bps_hac.cfg",
                             "dna_r9.4.1_450bps_sup.cfg",
                             "dna_r9.4.1_450bps_sup_plant.cfg",
                             "dna_r9.4.1_450bps_modbases_5mc_cg_fast.cfg",
                             "dna_r9.4.1_450bps_modbases_5mc_cg_hac.cfg",
                             "dna_r9.4.1_450bps_modbases_5mc_cg_sup.cfg",
                             "dna_r9.4.1_450bps_modbases_5hmc_5mc_cg_fast.cfg",
                             "dna_r9.4.1_450bps_modbases_5hmc_5mc_cg_hac.cfg",
                             "dna_r9.4.1_450bps_modbases_5hmc_5mc_cg_sup.cfg"]

[meta.protocol.flongle]
default_basecall_model = "dna_r9.4.1_450bps_hac.cfg"

[meta.protocol.gridion]
default_basecall_model = "dna_r9.4.1_450bps_hac.cfg"

# Minit/mk1c doesn't currently support the sup model
[meta.protocol.minit]
available_basecall_models = ["dna_r9.4.1_450bps_fast.cfg",
                             "dna_r9.4.1_450bps_hac.cfg",
                             "dna_r9.4.1_450bps_modbases_5mc_cg_fast.cfg",
                             "dna_r9.4.1_450bps_modbases_5mc_cg_hac.cfg",
                             "dna_r9.4.1_450bps_modbases_5hmc_5mc_cg_fast.cfg",
                             "dna_r9.4.1_450bps_modbases_5hmc_5mc_cg_hac.cfg"]
[meta.protocol.mk1c]
available_basecall_models = ["dna_r9.4.1_450bps_fast.cfg",
                             "dna_r9.4.1_450bps_hac.cfg",
                             "dna_r9.4.1_450bps_modbases_5mc_cg_fast.cfg",
                             "dna_r9.4.1_450bps_modbases_5mc_cg_hac.cfg",
                             "dna_r9.4.1_450bps_modbases_5hmc_5mc_cg_fast.cfg",
                             "dna_r9.4.1_450bps_modbases_5hmc_5mc_cg_hac.cfg"]

[meta.context_tags]
package = "bream4"
experiment_type = "genomic_dna"

[compatibility]
minknow_core = "5.0"
bream = "7.0.0"


[device]
import = "shared/default_device_settings.toml"
sample_rate = 4000
unblock_voltage = -300


[writer_configuration]
import = "shared/default_writer.toml"

[writer_configuration.sequencing_summary]
enable = [[1, 3000]]

[writer_configuration.read_fast5]
modifications_table = [[1,3000]]
raw = [[1,3000]]

[basecaller_configuration]
enable = false
enable_read_splitting = false

[basecaller_configuration.read_filtering]
min_qscore = 7

# Set via UI as there are no defaults known at build time
# [basecaller_configuration.alignment_configuration]
# reference_files = ["..."]
# bed_file = ""

# [basecaller_configuration.barcoding_configuration]
# barcoding_kits = []
# trim_barcodes = false
# require_barcodes_both_ends = false
# detect_mid_strand_barcodes = false
# min_score = 60
# min_score_rear = 60
# min_score_mid = 60


[analysis_configuration.read_detection]
mode = "transition"
minimum_delta_mean = 80.0
look_back = 2
break_reads_after_events = 250
break_reads_after_seconds = 0.4
break_reads_on_mux_changes = true
open_pore_min = 150.0
open_pore_max = 250.0

[analysis_configuration.read_classification]
classification_strategy = "modal"
selected_classifications = ["strand"]
scheme_module = "parsed"

[analysis_configuration.read_classification.parameters]
rules_in_execution_order = [
     "multiple=        (local_median,gt,350)&(local_median,lt,990)&(local_median_sd,gt,1.5)&(local_median_dwell,gt,0.005)&(duration,gt,0.02)",
     "pore_1=          (local_median,gt,160)&(local_median,lt,280)&(median_sd,gt,0.9)&(median_sd,lt,5)&(local_range,lt,35)&(duration,gt,15)",
     "pore=            (local_median,gt,160)&(local_median,lt,280)&(median_sd,gt,0.9)&(median_sd,lt,5)&(local_range,lt,35)",
     "event=           (median_before,gt,160)&(median_before,lt,280)&(median_before,gt,median)&(median,lt,140)&(median,gt,20)&(duration,lt,0.1)&(event_count,lt,20)",
     "adapter=         (median_before,gt,160)&(median_before,lt,280)&(median,lt,120)&(median,gt,50)&(event_count,lt,120)&(event_count,gt,7)&(median_sd,gt,1)&(median_sd,lt,5)&(local_range,lt,75)&(duration,lt,1)",
     "strand=          (local_median,gt,50)&(local_median,lt,150)&(local_range,gt,20)&(local_range,lt,44)&(local_median_sd,gt,0.9)&(local_median_sd,lt,5)&(event_count,gt,119)&(local_median_dwell,lt,0.006)",
     "strand2=         (local_median,gt,50)&(local_median,lt,150)&(local_range,gt,5)&(local_range,lt,44)&(local_median_sd,gt,0.9)&(local_median_sd,lt,5)&(event_count,gt,119)&(local_median_dwell,lt,0.015)",
     "unavailable=     (local_median,gt,10)&(local_median,lt,250)&(local_median_sd,gt,0.6)",
     "zero=            (local_median,gt,-25)&(local_median,lt,10)",
     "unknown_positive=(local_median,gt,0)&(local_median,lt,999)",
     "unknown_negative=(local_median,gt,-999)&(local_median,lt,0)"
]

[analysis_configuration.event_detection]
peak_height = 1.0
threshold = 4.13
window_size = 10
events_to_base_ratio = 1.8
break_on_mux_changes = true
max_mux_change_back_shift = 5

[analysis_configuration.channel_states]
import = "sequencing/sequencing_channel_states.toml"

###############################
# Sequencing Feature Settings #
###############################

# basic_settings #
[custom_settings]
simulation = "/home/artandi/Downloads/simul.FAST5"
enable_relative_unblock_voltage = true
unblock_voltage_gap = 480
run_time = 172800 # (seconds) 1hr=3600
start_bias_voltage = -185
# UI parameters
translocation_speed_min = 300
translocation_speed_max = 425

min_read_length_base_pairs = 200  # How many min bases to write out. Use table below to lookup read_length
min_read_length_lookup = {20 = 0, 200 = 119, 1000 = 600}

[custom_settings.temperature]
target = 34.0
timeout = 300
tolerance = 0.1
min_stable_duration = 15 # Seconds

[custom_settings.temperature.flongle]
target = 35.0

#-------- Channel States Disable ---------#

[custom_settings.channel_states_disable]
states_to_disable = ['multiple', 'saturated']
enabled = true

#-------- Group Manager ---------#

[custom_settings.group_manager]
# If this is true, and a channel becomes disabled/locked then swap the channel for another well if possible
swap_out_disabled_channels = true
# If this is True then when the groups determined by the mux scan reach the final mux it will loop back around to the
# first group. If this is disabled, once the groups have reached the last tier the channel will be disabled until the
# groups are refreshed, (by say another mux scan)
cycle_groups = false
# How many muxes to include per channel, if possible. Only applies if cycle_groups is true
cycle_limit_per_channel = 3
[custom_settings.group_manager.global_mux_change]
interval = 28800 # (seconds)
enabled = false

#-------- Global Flicks ---------#

[custom_settings.global_flick]
enabled = false

interval = 3600 # Timing between flicks (in seconds)

# voltage, pause, voltage, pause, voltage, pause
perform_relative_flick = true
rest_voltage = 0
rest_duration = 1.0
flick_duration = 3.0
voltage_gap = 300

#-------- Progressive Unblock ---------#

[custom_settings.progressive_unblock]
enabled = true

# A flick tier would go (flick for x seconds, rest for y seconds) * repeats
flick_duration = [ 0.1, 2.0, 10.0, 30.0 ]
rest_duration  = [   3,   3,   15, 30   ]
repeats        = [   1,   1,    4,  4   ]

states_to_flick = ['unavailable', 'zero'] # When see this, flick
states_to_reset = ['strand', 'pore', 'adapter' , 'event', 'locked', 'disabled'] # If any of these appear 'reset' the channel so it starts again

change_mux_after_last_tier = true # Feeds into group_manager. If this is true the channel is flagged to be replaced by group manager

[custom_settings.progressive_unblock.flongle]
rest_duration = [ 3, 3, 15, 300 ]

#-------- Drift Correction ---------#

[custom_settings.drift_correction]
enabled = false

interval = 600 # Try to correct this often (seconds)

setpoint = 30.0 # Try to keep (q90-q10) range close to this value (in pA)

channels_threshold = 50 # This many channels need to have classification to count
classification = "strand" # Use this as the source

### Small adjustment
lower_threshold = 0.8 # if average of observed medians is below the setpoint by this threshold then adjust
upper_threshold = 1.5 # if average of observed medians is above the setpoint by this threshold then adjust
initial_pA_adjustment_per_minimum_voltage_adjustment = 1

ewma_factor = 0.3 # exponentially weighted moving average weight factor. Closer to 1 == weight newest information more

voltage_fallback = -250 # Once voltage goes outside this, use fallback static
voltage_fallback_interval = 5400 # If not corrected in this long (seconds), or in fallback, adjust by the minimum_voltage_adjustment

# Don't go out of these limits
voltage_max = -170
voltage_min = -250

[custom_settings.drift_correction.flongle]
channels_threshold = 5 # A lot less channels to work with

[custom_settings.static_drift_correction]
enabled = false

interval = 5400 # Correct this often (seconds)
voltage_max = -170
voltage_min = -250

############
# Mux Scan #
############

[custom_settings.mux_scan]

# ---   classify_well   --- #
threshold = 2.5  # 2.5 seconds of time in well must be pore/strand/adapter to be eligible to be picked
states_to_count = ['pore', 'strand', 'adapter', 'event']

# ---   report generation   --- #
enable_ping = true   # Whether to ping the mux scan
enable_report = true  # Whether to output data to the log directory

# ---   routine settings   --- #
enabled = true
collect_0mv_readings = true
collection_time_per_well = 10  # How long to look at each well for
interval = 5400  # (seconds) 1hr=3600
initial_global_flick = true
realign_offset_for_group_1 = true

# ---   Well Filtering    --- #
enable_reserve_pore = true  # boolean indicating if reserve pore will be used to filter channels
reserve_voltage_offset_threshold = -10

# ---   Channel Ordering   --- #
priorities = ['intercept', 'total_good_samples']
# A list of the metrics to use to priorities the wells of a channel
priorities_sort_ascending = [false, false]

[custom_settings.mux_scan.flongle]
enable_reserve_pore = false

# ---   Offset Calibration --- #
[custom_settings.mux_scan.offset_calibration]
voltage_steps = [-10, -20, -30]
muxes = [1, 2, 3, 4]
collection_time = 1
minimum_conductance = 0.6
maximum_conductance = 1.4
maximum_confidence = 50
minimum_confidence = -50
maximum_adjustment = 300
min_wells = 20

[custom_settings.mux_scan.offset_calibration.flongle]
min_wells = 2

# ---   Global Flick Config   --- #
[custom_settings.mux_scan.global_flick]
enabled = true
perform_relative_flick = true
rest_voltage = 0
rest_duration = 1.0
flick_duration = 3.0
voltage_gap = 300

[custom_settings.mux_scan_progressive_unblock]
enabled = true

# A flick tier would go (flick for x seconds, rest for y seconds) * repeats
flick_duration = [ 0.1, 2.0, 10.0, 30.0 ]
rest_duration  = [   3,   3,   15, 30   ]
repeats        = [   1,   1,    4,  4   ]

states_to_flick = ['unavailable'] # When see this, flick
states_to_reset = ['strand', 'pore', 'adapter' , 'event', 'locked', 'disabled'] # If any of these appear 'reset' the channel so it starts again

change_mux_after_last_tier = true # Feeds into group_manager. If this is true the channel is flagged to be replaced by group manager


#####################
# Channel Wind Down #
#####################

[custom_settings.channel_wind_down]
timeout = 60
enabled = true

[custom_settings.channel_wind_down.channel_states_disable]
states_to_disable = ['pore', 'saturated', 'multiple', 'unknown_negative', 'unknown_positive', 'zero']
enabled = true
stop_feature_manage_enabled = true
min_channel_threshold = 10
active_states = ['strand']

[custom_settings.channel_wind_down.channel_states_disable.flongle]
min_channel_threshold = 2

[custom_settings.channel_wind_down.progressive_unblock]
enabled = true

# A flick tier would go (flick for x seconds, rest for y seconds) * repeats
flick_duration = [ 0.1, 2.0, 10.0, 30.0 ]
rest_duration  = [   3,   3,   3, 3   ]
repeats        = [   1,   1,    4,  4   ]

states_to_flick = ['unavailable', 'zero'] # When see this, flick
states_to_reset = ['strand', 'pore', 'adapter' , 'event', 'locked', 'disabled'] # If any of these appear 'reset' the channel so it starts again

change_mux_after_last_tier = true # Feeds into group_manager. If this is true the channel is flagged to be replaced by group manager



##################
#   Read Until   #
##################

[custom_processes.read_until]
script = "sequencing/read_until/read_until_script.py"
enabled = false

# See the read until script argparse for parameters to pass
# Anything passed by the UI will be on the end of this
arguments = ["--guppy_config=dna_r9.4.1_450bps_fast.cfg", "--enrich_unblock_min_sequence_length=200"]

[custom_processes.read_until.mk1c]
arguments = ["--guppy_config=dna_r9.4.1_450bps_sketch.cfg", "--enrich_unblock_min_sequence_length=200"]
`

**Comment by santiago-es** [comment]
Here is my toml file I am attempting to use: 


https://pastebin.com/YBFy38UZ

**Comment by santiago-es** [comment]
as an update: I've tried with 2 different configuration test cells and MK1Bs, runs into the same issue. I imagine its an issue with my .toml file or the ability of the MinION to correctly point to it when setting up the run.

**Comment by nick297** [comment]
Are you running readfish yet, or just the simulation when you get the error? Your toml file looked fine to me, but the authors will be better judges of that.

**Comment by santiago-es** [comment]
I was able to successfully install readfish in a conda environment, but i havent been able to even get the simulation to start. After restarting my computer, my minknow gui is now asking me for the host server so I think I'm making some progress.

**Comment by santiago-es** [comment]
Thanks for this alex. I'm attempting to try it but after reboot my MinKnow is stuck on a connection manager page and doesnt navigate to the gui with the MinION connection im used to so working on solving that atm

**Comment by santiago-es** [comment]
I'm back haha. 

So I was able to successfully unblock all reads and moved on to testing an enrichment on the playback data.

First I started my guppy_basecall_server with: 

`guppy_basecall_server --config dna_r9.4.1_450bps_fast.cfg -p 5555 -l /tmp/guppy`

I placed the basecall server ip and port# in my .toml file (which is the one from the tutorial / README with the appropriate edits). 

I then ran:
`readfish targets --device MS00000 --experiment-name target2 --toml human_chr_selection.toml --log-file ru_test.log --port 9502
`
which seems to successfully connect but then the throttle times are much slower than expected: 

![image](https://user-images.githubusercontent.com/10642529/178078513-a10ec1ee-58ba-42d3-aa6c-d550118429a1.png)

What might be going on here? 

Here is my toml file for reference, I changed it to only select for chr1 

![image](https://user-images.githubusercontent.com/10642529/178078572-d8883e8e-bd65-4a5c-a41e-52e7ee15f29c.png)

I'm using the guppy6_minknow5 branch

**Comment by santiago-es** [comment]
OK, I think I figured it out! 

I think the final issue that popped up was my GPU basecalling was misconfigured. 

For others who may have this same issue on the guppy6_minknow5 branch here is what works from start to finish:

[Follow Miles Benton's instructions ](https://hackmd.io/@Miles/ryVAI_KWF#minknowservice )for live GPU basecalling. I got this to work on Ubuntu 22 with the Ubuntu 20 repos, Guppy 6 and Minknow-core 5.1

Next install readfish following the guppy6_minknow5 branch instructions. 

Before beginning a simulation, it will be necessary to stop the minknow service. On Linux you do this with:

`sudo service minknow stop`

Then run `sudo /opt/ont/minknow/bin/mk_manager_svc --simulated-minion-devices 1`

pointing to whatever the appropriate folder is for your Minknow installations bin. this starts MinKnow with a simulated device.

When it comes time to unblock, it will be necessary to reload scripts by clicking three dots on the top right of the experiment start / run-naming page of the MinKNOW GUI after editing the ***_sequencing***.toml file for a simulated run.

After that the readfish instructions should work appropriately and you should see the gpu basecalling work appropriately.
