### ISSUE TITLE
readfish not work

### ISSUE THREAD

**Issue by windforclouds** [LooseLab/readfish#206]
we had some problems，when we open readfish, you can see this
minknowcore 5.0.0 ; guppy 6.0.7 ; minknow 22.03.6
![image](https://user-images.githubusercontent.com/46742903/180951272-32c86132-a736-4ee0-93f6-4a4bef1fe8e9.png)

**Comment by windforclouds** [comment]
$cat human_chr_selection.toml
[caller_settings]
config_name = "dna_r9.4.1_450bps_fast"
host = "ipc:///tmp/.guppy"
#host = "127.0.0.1"
port = 5555

[conditions]
reference = "/data/test/02.readfish/ref_hg19/ucsc.hg19_NC_012920.1.mmi"

[conditions.0]
name = "select_chr_21_22"
control = false
min_chunks = 0
max_chunks = inf
targets = "/data/test/02.readfish/rawdata/ontarget.txt"
single_on = "stop_receiving"
multi_on = "stop_receiving"
single_off = "unblock"
multi_off = "unblock"
no_seq = "proceed"
no_map = "proceed"
#targets = ["chr21", "chr22"]

**Comment by Adoni5** [comment]
Hi @windforclouds - Do you still need need help with this? 
Could you let me know what branch of the readfish repository you are working with? 
The immediate issue that I can spot is that MinKNOW no longer uses the 9501 port for GRPC, as this is the port is used to listen on for unencrypted connections, but instead listens on the 9502 port for secured connections.
