### ISSUE TITLE
Specifying targets in a bed file

### ISSUE THREAD

**Issue by wdecoster** [LooseLab/readfish#22]
I could not find this in the documentation, apologies if I missed it, but I think a common use-case would be to have the targets of interest specified as intervals in a bed file. I noticed the [conditions.0] 'targets' part either takes a string or an array of targets, or could it also be a (bed) file?

Thanks,
Wouter

**Comment by alexomics** [comment]
This is something that we want to incorporate. It will definitely make downstream analysis easier!

**Comment by wdecoster** [comment]
So right now that's not yet possible?
Then we will put our targets in the toml format in an array, and we then use coordinates in `chr1:123456-234567` format?

**Comment by mattloose** [comment]
It's almost possible... You can give a file as the parameter for a target: 

e.g.

targets = "/path/to/your/targets/cancer_panel_and_MHC_targets.txt"

And that file will be of the following form:

chrX,71234624,71259140,+
chr19,53516024,53585269,+
chr12,6661648,6694510,+
chr19,21500564,21543078,+
chr7,57114614,57144864,+
chr18,25056926,25357152,+
chr22,28878592,29062487,+
chrX,15785472,15828260,+
chr6,28452797,33473354,+
chr6,28452797,33473354,-

So it isn't yet (quite) a bed file - but its close. Note the strand information. - so it's chr,start,stop,strand

**Comment by alexomics** [comment]
So currently, the targets are only in the formats:
```text
chr1
```
or 
```text
chr1,0,1000,+
```

These should fit the patterns:
```
"^[^,]+$"
"^.+,[0-9]+,[0-9]+,[+-]$"
```

**Comment by mattloose** [comment]
Like what Alex said ;-)

**Comment by wdecoster** [comment]
Alright, we can work with that! Thanks!

You have me confused here for a bit that we need to specify the strand. Won't the alignment consider the reverse complement by default?

**Comment by mattloose** [comment]
The aligner does, but this is to capture the case where you are targetting say a 10 kb region with reads of mean length 10 kb. You might want to offset your target regions such that you capture any read which starts within 5kb upstream of your target. So your target might be:
chr1:10000-20000
But you might target:

chr1,5000,20000,+
chr1,10000,25000,-

This would capture reads that have some probability of extending in to your region of interest.

Does that make sense?

It may be over-engineered right now which is why we are going to make a bed format compatible (with possibly automatic self correcting strand offsettting - PASCSO?! down the line!).

**Comment by wdecoster** [comment]
Ah gotcha. I already padded the intervals to take those flanking-potentially-on-target reads into account, but indeed not strand specific.

**Comment by alexomics** [comment]
@wdecoster I've added some description to the [TOML.md](https://github.com/LooseLab/ru/blob/bb67f539b8dd09cd1b5e7c323d971899d32a5fb6/TOML.md#target-types) file. Does this make things clearer?

**Comment by wdecoster** [comment]
Yep, all clear now!

**Comment by ythuang0522** [comment]
@mattloose We are still not quite sure of this bed formatting. Our interpretation is, for any given target gene, e.g., chrX,71234624,71259140, we must duplicate two coordinates in the target file even without extension.
 i.e., 

> chrX,71234624,71259140,+
> chrX,71234624,71259140, -. 

Without this duplication we will miss half alignments on one strand. Is that true?

**Comment by alexomics** [comment]
@ythuang0522 Yes, to cover both strands you must specify both `+` and `-`.

**Comment by ythuang0522** [comment]
Thank you.
