### ISSUE TITLE
Question R10/Q20+ barcoding

### ISSUE THREAD

**Issue by Arne-OHMX** [LooseLab/readfish#230]
Hi all,

I was wondering if it is possible to use barcode-aware readfish with R10 flow-cells.
The only information I found about R10 was #163 

We are currently using the `dev_staging readfish 0.0.11a3 ` would this have to be changed if the above is possible?

**Comment by mattloose** [comment]
We are working on a slightly updated version available in the next couple of weeks which should enable this in a clearer way.
