### ISSUE TITLE
Documentation for "summary" command? ("alt" and "random" rows?)

### ISSUE THREAD

**Issue by danchurch** [LooseLab/readfish#243]
Hi there, where is the info for interpretation of outputs from the `readfish summary` command? 

Most of the headers are self-explanatory but I am uncertain about the "_alt" and "_random" rows that appear in some of my summary reports. I would like to know more about these.

**Comment by alexomics** [comment]
Can you share the context that you are seeing this? I think that those might be contig names from your reference.

**Comment by danchurch** [comment]
Oh jeez, sorry. Yes, just found them in the fasta.  Apologies.

**Comment by alexomics** [comment]
No worries!
