### ISSUE TITLE
update example readfish toml file?

### ISSUE THREAD

**Issue by danchurch** [LooseLab/readfish#252]
Hello LooseLab,

Thanks again for the awesome software. I just wanted to ask, is the example [readfish toml file](https://github.com/LooseLab/readfish/blob/dev_staging/examples/human_chr_selection.toml) a little out of date? To make it work, I had to change line 3, with my own setup, I had to change the host from the localhost ip address to the socket/pipe/whatever-it-is created for guppy server/client. As in:

`host = "127.0.0.1`

to

`host= "ipc:///tmp/.guppy/`

If this is a generalizable issue, perhaps the example toml file in this repo should be updated?

**Comment by Adoni5** [comment]
Hi @danchurch - Good spot! We are _on the cusp_ of releasing an updated and consolidated version of readfish, with all shiny updated documentation and examples. But in the mean time I will update the example toml file in `dev_staging`!
