### ISSUE TITLE
OSX Silicon install issue grpcio

### ISSUE THREAD

**Issue by mattloose** [LooseLab/readfish#278]
https://github.com/LooseLab/readfish/blob/f128f4b1c6dd108fa858f6a3e4224693f26ca442/README.md?plain=1#L86

This yml file may result in a version of readfish that cannot run on OSX Silicon.

The temporary work around is to uninstall grpcio:

```
pip uninstall grpcio
```

and then reinstall with:
```
GRPC_PYTHON_LDFLAGS=" -framework CoreFoundation" pip install grpcio --no-binary :all:
```

**Comment by Adoni5** [comment]
Closed in #300
