### ISSUE TITLE
Provide PromethION Bulkfiles

### ISSUE THREAD

**Issue by mattloose** [LooseLab/readfish#284]
5khz gridION bulkfile is now available. Will generate approriate data for PromethION soon.

_Originally posted by @mattloose in https://github.com/LooseLab/readfish/issues/268#issuecomment-1755805340_
            

In the near furture provide some promethION bulkfiles for data testing.

**Comment by Adoni5** [comment]
There is a 4KhZ Prom bulk file up - is that sufficient?

**Comment by Adoni5** [comment]
Somebody remember to make one at some point
