### ISSUE TITLE
Argument should be in base args?

### ISSUE THREAD

**Issue by mattloose** [LooseLab/readfish#308]
https://github.com/LooseLab/readfish/blob/beb3dffcf96d287e615903032238d231c8498c7f/src/readfish/entry_points/targets.py#L109-L114

Given this is controlling a log file that is specified elsewhere I think this should be alongside base args?

**Comment by Adoni5** [comment]
I agree with default enabled being superfluous - but I don't follow about this controlling a log "specified elsewhere"? Can you expand a bit?

**Comment by Adoni5** [comment]
@mattloose any updates

**Comment by mattloose** [comment]
good question.
I don't remember.

**Comment by Adoni5** [comment]
Unmemorable
