### ISSUE TITLE
Unblock time incorrectly specified as int

### ISSUE THREAD

**Issue by mattloose** [LooseLab/readfish#312]
https://github.com/LooseLab/readfish/blob/fabf9bfac796f7e72cc9d8cfbdbdcd64d34bf9e3/src/readfish/_cli_args.py#L92

Unblock time should be specified as a float, not an int. The default specified is a float. Manually setting an alternative float value causes arg parsing to fail.

**Comment by Adoni5** [comment]
Closed in #310
