### ISSUE TITLE
cannot find guppy_6 branch

### ISSUE THREAD

**Issue by bjaysheel** [LooseLab/readfish#318]
Hi, I am following install guide to install boss-runs and readfish for adaptive sampling, but when trying to install readfish using the command

  `pip install git+https://github.com/LooseLab/readfish@guppy_6`

I get an error 

`Cloning https://github.com/LooseLab/readfish (to revision guppy_6) to /tmp/pip-req-build-ghi3ob0f`
`Running command git clone --filter=blob:none --quiet https://github.com/LooseLab/readfish /tmp/pip-req-build-ghi3ob0f`
 `WARNING: Did not find branch or tag 'guppy_6', assuming revision or ref.`
  `Running command git checkout -q guppy_6`
     `error: pathspec 'guppy_6' did not match any file(s) known to git`
     `error: subprocess-exited-with-error`

Looks like the branch no long exists, wonder if the is a recent change as I ran the same install process about a month ago and everything seem to have worked at that time.

Thank you

**Comment by Adoni5** [comment]
Hi @bjaysheel - we indeed removed that branch, as we have majorly refactored readfish. A BOSS-RUNS plugin is on our roadmap (somewhere).

You should be able to find working code that is compatible with BOSS-RUNS under our releases [here](https://github.com/LooseLab/readfish/releases/tag/BossRuns%2FV0.0.2).

This is just source code, but you can extract the source code folder, `cd` into it and run either 

`pip install -e .` to install into the current python environment  or equally `python setup install` should work. All the other requirements (`ont-pyguppy-client-lib` and `read-until`) should be installed according to the instructions you were following.

Let me know if this doesn't work
Rory

**Comment by bjaysheel** [comment]
Hi Rory, thank you for the reply.  I was able install readfish based on the link above.  Let you know if I run into any other issues with adaptive sampling.

Thank you
Jaysheel
