### ISSUE TITLE
readfish stats

### ISSUE THREAD

**Issue by alexomics** [LooseLab/readfish#325]
Dear Team,

I do have another issue. I tried to analyze the results using `readfish stats` with the `--toml` and `--fastq-directory` arguments. However, I see an error
```
(Channel 72 not found in Channel Map or', ' Barcode barcode48 not found in toml human_chr_selection.toml')
```

My toml file has the same content as the original human_chr_selection.toml file except for the file path to the reference mmi file. I suspect that I have to create a TOML table named `barcodes` and specify each of the barcodes within the toml file. Is this the way to go? Alternatively, could it be that the file path to the `--fastq-directory` is wrong? In this case, I specified the filepath to the run directory (e.g., `/data/AFO_V3`) or the file path to the fastq_pass directory (e.g., `/data/AFO_V3/sample1/20240125_1411_MS00000_id_XXXXX/fastq_pass`). I also tried to specify the file path to a specific barcode directory hosting  fastq files  (E.g., `/data/AFO_V3/sample1/20240125_1411_MS00000_id_XXXXX/fastq_pass/barcode01`). However, I still encountered the same error.

_Originally posted by @ayoraind in https://github.com/LooseLab/readfish/issues/221#issuecomment-1918765115_

**Comment by mattloose** [comment]
Hi,

You say you used the human_chr_selection.toml file - is this the one shown here: 

https://github.com/LooseLab/readfish/blob/main/docs/_static/example_tomls/human_chr_selection.toml

This toml file is not necessarily compatible with barcoded runs for analysis with readfish stats - did you use this toml in the generation of the data? The data you are looking at are obviosuly barcoded and readfish stats will be assuming that (and inferring it from the reads).

If you did run adaptive sampling on a barcoded run with tthe human_chr_select.toml then we might need to tweak the readfish stats program to better handle this.

The adaptive sampling experiment should have worked regardless.

**Comment by ayoraind** [comment]
Yes, I used the human_chr_selection.toml file shown in the link you posted. I ran adaptive sampling using the `human_chr_select.toml` file. 

The (stop-gap) solution was to 
- copy lines 95-136 from the `human_regions_barcoded.toml` file (https://github.com/LooseLab/readfish/blob/main/docs/_static/example_tomls/human_regions_barcoded.toml) into the `human_chr_select.toml` file, 
- change `[barcodes.barcode01]` to `[barcodes.barcode48]`, 
- run `readfish validate` to be sure it's valid, 
- re-run the `readfish stats` command. 

Seems to be working so far, although it is taking quite a while to align the FASTQ (currently at 2hr 33 minutes).

**Comment by mattloose** [comment]
OK - that's a plausible workaround. Let us know what the results look like - I'm not quite sure how it will behave.

**Comment by ayoraind** [comment]
Seems like it worked. I got the stats after 3hrs 54 minutes.

![image](https://github.com/LooseLab/readfish/assets/43066737/818aacb7-8ac0-41ad-a6aa-c6ad841cfc46)

**Comment by bjaysheel** [comment]
Hi,
   What fastq-directory was used for stats, the fastq_pass directory or the root of output folder as you indicated in your first post?

**Comment by ayoraind** [comment]
Hi @bjaysheel,

I specified the file path to the run directory (e.g., /data/AFO_V3).
