### ISSUE TITLE
readfish validate reference file name check

### ISSUE THREAD

**Issue by speleonut** [LooseLab/readfish#326]
Hi Matt & Alex,
There is a potential bug in the reference file check which causes the following error message:
"readfish.validate Provided index file appears to be of an incorrect type - should be one of ['.fasta', '.fna', '.fsa', '.fa', '.fastq', '.fq', '.fasta.gz', '.fna.gz', '.fsa.gz', '.fa.gz', '.fastq.gz', '.fq.gz', '.mmi']"
If the filename has a "." then the reference will be marked as the incorrect type, even if it is correct: e.g.
`GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.mmi` causes the error
`GCA_000001405_15_GRCh38_no_alt_analysis_set.mmi` does not.
A simple work around is to create a soft link with an acceptable file name.  
Perhaps in src/readfish/plugins/_mappy.py (lines 90 - 96) testing the suffixes only at position [-1] first, then if it fails testing only suffixes at positions [-2:] for any given index file would solve this problem.  My python skills are limited or I would just suggest a patch...
Cheers,
Mark

**Comment by mattloose** [comment]
Thanks for highlighting this - it is a good point and we will address in a futre release.

**Comment by Adoni5** [comment]
Fixed in #330
