### ISSUE TITLE
Example barcode balancing

### ISSUE THREAD

**Issue by ahfitzpa** [LooseLab/readfish#333]
Hi, 

We are interested in using the barcode balancing feature in amplicon ONT workflows. It is not clear to me in the documentation whether or not the barcode balancing with readfish requires an input file as it is a form of adaptive sampling. 

If an input file (fasta, mmi) is required, what should it contain? 

1) Barcode sequences
2) Barcode + amplicon sequences

Thank you for the clarification. 

Amy

**Comment by mattloose** [comment]
Reopening as need to address this.
