### ISSUE TITLE
readfish stats on-target median read length and N50 always 0B

### ISSUE THREAD

**Issue by maximilianmordig** [LooseLab/readfish#334]
I think there is an error in the table output by `readfish stats` which also appears in the table in the README.md of this repo. When enriching for `chr20,21`, the median read length and N50 seem to be reported in the off-target rather than the on-target columns (the entire on-target colum is 0b).

Moreover, can you explain how you define on- and off-target in case of multiple alignments to the target and off the target? If a read aligns to both the target and off the target, do you count it in both columns of Alignments.On-Target and Alignments.Off-Target?
Is the estimated coverage for the whole contig? It may make sense to also split by on- and off-target, similarly to the other columns.

**Comment by mattloose** [comment]
Hi,

Thanks for trying out the tool.

I agree the presentation of the on target and off target data in the table is a little confusing in the case where a whole chromosome is presented. In this example there is no on target and off target with respect to chromosomes 20 and 21 as the whole chromosome is the target. Thus the numbers (although incorrectly shown in the off target column) are correct - I will flag this for checking though (@Adoni5) .

> Moreover, can you explain how you define on- and off-target in case of multiple alignments to the target and off the target? If a read aligns to both the target and off the target, do you count it in both columns of Alignments.On-Target and Alignments.Off-Target?

So this can be answered and is based on the decision that should be made derived from the toml file used to configure the experiment. Reads will be assigned to on target and off target following the logic defined in there - so "on target" should equate to "stop_receiving" and "off target" should be "unblock". You can choose how such mappings are handled in the readfish toml (multi_on and multi_off) - see https://looselab.github.io/readfish/toml.html#regions-sub-tables for more information.

The idea behind readfish stats is to evaluate the experiment in the context of the original analysis set up.

I hope that helps.
