### ISSUE TITLE
Readfish and boss-runs in 2024

### ISSUE THREAD

**Issue by jelber2** [LooseLab/readfish#335]
Hi,

I have been  following Readfish for a while and am also familiar with BOSS-RUNS (although only have now considered the idea of venturing out into these open-source alternatives to MinKNOW). I guess my general question is the possibility of using recent MinKNOW versions (late 2023 with dorado) with Readfish and BOSS-RUNS (that appears to be abandon-ware now given the lack of answers to Github Issues) on either using a GridION or P2Solo connected to the GridION.

Looking forward to hearing back from you,
Jean Elbers

**Comment by Adoni5** [comment]
HI @jelber2 
There is no reason Boss Runs wouldn't work with The latest MinKNOW and Dorado, provided you output FASTQ when basecalling.

There is a milestone for `readfish` to reincorporate Boss Runs support into the latest refactored release, however this is not a top priority for me at the moment. So it would be necessary to use this tagged [release](https://github.com/LooseLab/readfish/releases/tag/BossRuns%2FV0.0.2).

**Comment by jelber2** [comment]
@Adoni5 thanks! I will give Readfish and boss-runs a try !
