### ISSUE TITLE
readfish with just depletion?

### ISSUE THREAD

**Issue by josephhughes** [LooseLab/readfish#336]
Hi,

Is it possible to use readfish if I just want to deplete the known host genome but I don't know what other microbes might be in the sample and these are the reads I want sequenced?

**Comment by mattloose** [comment]
Hi,

Yes it is - you would simply configure your toml file to reject everything in the reference and only sequence things that do not map to the reference.

https://github.com/LooseLab/readfish/blob/main/docs/_static/example_tomls/human_chr_depletion.toml

Essentially modify this toml file to reject all chromosomes (depending on your reference this might include unbplaced squences, alt chromosomes and mitochondria) and sequence anything that does not map.  The other change you would have to make is on the "above_max_chunks" parameter. In the region in the linked file it is set to unblock. You would want to set it to "stop_receiving". This would have the effect of sequencing any read that did not map to your reference (see below).

Matt

[[regions]]
# Name of the region.
name = "All Targets"
min_chunks = 1 # minimum number of chunks before a decision can be made
max_chunks = 4 # maximum number of chunks to use in decision making - after this perform the above_max_chunks action
targets = ["chr1" ... "chrM"]
single_on = "unblock"         # Action to take if there is one mapping on target.
multi_on = "unblock"          # Action to take if there is more than one mapping, with at least one target.
single_off = "stop_receiving" # Action to take if there is one mapping and it is off target
multi_off = "stop_receiving"  # Action to take if there are multiple mappings, where all are off target.
no_seq = "proceed"            # Action to take if no sequence data.
no_map = "proceed"            # Action to take if no alignments returned.
above_max_chunks = "stop_receiving"  # Action to take if above max_chunks.
below_min_chunks = "proceed"  # Action to take if below min_chunks.

**Comment by josephhughes** [comment]
Fab!
Thanks, J.
