### ISSUE TITLE
Not being able to finish the tutorial/test

### ISSUE THREAD

**Issue by franztastic** [LooseLab/readfish#337]
Hi everyone,
First of all, thanks for the nice program, I'm excited to have it aaalmost working...  After few days handling all the problems with the permissions, I'm trying to run the tutorial experiment and I'm facing a "RUN ERROR" just a minute after starting it. 

I have a MinKNOW v. 5.8.6, Dorado 7.2.13 and running in a UBUNTU 22.04.4.

![Screenshot at 2024-02-27 16-47-03](https://github.com/LooseLab/readfish/assets/8795082/a969f8d2-ca0c-4756-8083-2fdd2f32c909)

Here are the logs obtained of the experiment.
[control_server_log-0.txt](https://github.com/LooseLab/readfish/files/14422201/control_server_log-0.txt)
It says something regarding a callibration set, but I'm sure I haven't changed anything about callibration... 

Thank you very much for your help, best wishes and have a nice day!

**Comment by alexomics** [comment]
Hi there, it looks like you are running the simulation using the original demo bulk FAST5 file that we provided. This was sequenced on a MinION flow cell, for PromethION you will need a different bulk FAST5 file which you can find under the "Configuring bulk FAST5 file Playback" header here: https://looselab.github.io/readfish/getting-started.html. Currently that bulk FAST5 file is at: https://s3.amazonaws.com/nanopore-human-wgs/bulkfile/PC24B243_20220512_1516_PAK21362_3H_sequencing_run_NA12878_sheared20kb_3d5147fc.fast5 This file is approx 35Gb in size.

**Comment by alexomics** [comment]
Fantastic! If you hit any other problems feel free to open another issue 😊

**Comment by bioteksampath** [comment]
Hi @franztastic and @alexomics,

I have same RUN ERROR issue on my demo run with in minutes of loading MinION data using playback option in MinKnow UI. I have a MinKnow with Dorado and running in a UBUNTU 22

Not sure where should I start? I currently struck at this step - https://github.com/LooseLab/readfish?tab=readme-ov-file#configuring-bulk-fast5-file-playback


![Screenshot from 2024-04-09 10-31-19](https://github.com/LooseLab/readfish/assets/8802351/23d83acb-84b8-48bf-85ee-2ef3a5e38907)

@franztastic Wondering, what are permission error I should be checking.
I do have full permission on 5555

```
$ ll /tmp/.guppy/
srwxrwxrwx 1 minknow minknow 0 Mar 28 09:04 5555
```

Thanks for your help,
sam

**Comment by bioteksampath** [comment]
@alexomics 
thanks for your prompt respose:
im using this file
 `
GXB02001_20230509_1250_FAW79338_X3_sequencing_run_NA12878_B1_19382aa5_ef4362cd.fast5
`
