### ISSUE TITLE
location of readfish output

### ISSUE THREAD

**Issue by bjaysheel** [LooseLab/readfish#339]
Hi,
  I have setup a playback run using MinKNOW v5.8.13, minION MK1B, selected all default options and using readfish for basecalling.  I can't figure out from the documentation where is the output.  
  
   a.) Is the data stored in minKnow/data folder (from minKNOW GUI) the same as the output for readfish?  or 
   b.) Is the file listed in debug_log for guppy and mappy_rs in the readfish toml file the final output of readfish.

   if option a, I don't see a consolidated .fastq file just folder called fastq_pass and fastq_fail, does that mean something went wrong or am I missing a step/option in minKNOW.

Thanks
Jaysheel 
    
here is the toml file, and command used to run readfish

`[caller_settings.guppy]
config = "dna_r10.4.1_e8.2_400bps_5khz_hac"
address = "ipc:///nanopore/5000"
debug_log = "pathogen_selection_basecalled_chunks.fq"

[mapper_settings.mappy_rs]
fn_idx_in = "/nanopore/ref/Pathogen_contigs_samba_M1000.fa"
n_threads = 4
debug_log = "pathogen_selection_mapped_chunks.paf"
best_n = 1

[[regions]]
name = "select_pathogen"
control = false
min_chunks = 0
max_chunks = 4
targets = "/nanopore/ref/Pathogen_contigs.name"
single_on = "stop_receiving"
multi_on = "stop_receiving"
single_off = "unblock"
multi_off = "unblock"
no_seq = "proceed"
no_map = "proceed"
above_max_chunks = "unblock"
below_min_chunks = "proceed"
`

`readfish targets --device MN44041 --experiment-name "SimulateRun_ReadFish_Pathogen_Selection" --toml /nanopore/readfish_pathogen_selection.toml --log-file pathogen_selection_run1.log --debug-log pathogen_selection_run1_chunks.tsv`

**Comment by mattloose** [comment]
Hi,

Thanks for your interest in using readfish. The final output is the reads that are contained within the fastq_pass and fastq_fail folders  - i.e the reads that have been written as a consequence of running readfish during sequence. 

The various log files written by readfish contain information about what readfish was doing. 

I hope this helps?
