### ISSUE TITLE
Choice of parameters

### ISSUE THREAD

**Issue by JensUweUlrich** [LooseLab/readfish#35]
Hi,

Some weeks ago, we did a sequencing run to test ReadUntil without reference mapping and basecalling. Everything went fine and I could recognize a peak at 500bp as expected. But after 3 hours I observed, that a lot of action messages were failed and the read lengths were increasing on unblocked channels. Now I wonder if this could be caused by the parameters I selected for running ReadUntil (e.g. action batch size 100, unblock_duration 1.0). I'm not sure whether I completely understand how the parameters influence the behaviour of the gRPC stream. Do you have any suggestions for parameter choice?

Thanks
Jens

**Comment by mattloose** [comment]
HI Jens - can you provide any more details on the read distribution you were seeing? Do you have any plots that show the changes over time. Were you running playback or was it a real run? We do see some longer reads which slip through - but without seeing some details it's difficult to comment.

Matt

**Comment by JensUweUlrich** [comment]
Hi Matt,
thanks for your quick reply. It was a real run on a MinION with a 9.4.1 Flowcell. I made some plots showing the data from the experiment. First you can see how the end reason of sequenced reads is changing over time, with a drop in unblocking of reads after approximately 3 hours.
![EndReason_EvenCh_OddRds](https://user-images.githubusercontent.com/46562264/78708026-bff30080-7911-11ea-8a2a-12f9eb6a4314.png)

The second plot shows the read distribution over time. You can see, that there is a rise in the read lengths after approx. 9000 seconds (2.5h) .
![ReadLength_EvenCh_OddRds](https://user-images.githubusercontent.com/46562264/78708303-31cb4a00-7912-11ea-9f9b-58e331e3a417.png)

I wonder if there is a queue or cache at the MinKNOW server, that stores received gRPC action requests from the ReadUntil Client and throws them away when it is overflown. Or is that behaviour related to some network issues? Have you experienced something similar?

Thanks
Jens

**Comment by mattloose** [comment]
Hi Jens,

This doesn't really make sense - can you provide the specific command that you ran and any configuration files you used?

Can you specify what you mean by action messages were failed?

Thanks,

Matt
