### ISSUE TITLE
toml_live not updated upon changes

### ISSUE THREAD

**Issue by lborcard** [LooseLab/readfish#371]
Dear Readfish team,

I am testing your toml_live option but since the documentation does not cover exactly how to use it (to my knowledge) is there anything covering this topic?
I tried to create a toml file using `my.toml_live` and then modify it during a simulated run but to no avail. I could not see any trace of an update of the TOML file.

What did I do wrong?
best,

Loïc

**Comment by mattloose** [comment]
Hi,

You create a toml as normal, but then during a run add a new toml with the same name but _live at the end. 

This should work, but as you know it's not extnesively documented at present.

I'd run on a playback run first and test. You should see a message in the logs when the toml file is re-read.

**Comment by alexomics** [comment]
The live toml file should have the same name as the original with `_live` added at the end of the `.toml` extension. So:
```text
exp.toml
exp.toml_live
```

Can you confirm that you have followed this naming scheme? Also, when reloading the TOML if the `_live` is not valid it is ignored, but readfish will attempt to reload each iteration.

**Comment by lborcard** [comment]
ok thank you very much ! now this toml can further modified and each modification will be noticed?

**Comment by mattloose** [comment]
Yes - as long as the toml file is valid it will be loaded on each iteration - but currently we don't check the validity and it's left to the user to make sure that the file is valid.

**Comment by lborcard** [comment]
alright perfect thank you very much!
