### ISSUE TITLE
Off-target region with high mapping reads

### ISSUE THREAD

**Issue by HJTsai** [LooseLab/readfish#55]
Hi,

We run a cosmic panel in NB4 cells and found a off-target region (MIR12136) with high mapping reads.
We wonder to know whether this off-target result was observed in your experiment?

![圖片1](https://user-images.githubusercontent.com/49969700/84160492-d13ac380-aaa0-11ea-9631-ef5929d5a278.jpg)

Amber

**Comment by mattloose** [comment]
I've not checked in NB4 samples, but I've looked and seen this in NA12878 - I've not looked at the mapping that causes this - would be interesting to dig in to further.

**Comment by HJTsai** [comment]
Hi Matt,

We found this off target region was within the reported segmental duplications region.

![image](https://user-images.githubusercontent.com/49969700/84644822-42132d00-af32-11ea-9a70-85a611e647b3.png)

We are amazing your NB4 cells result with 16 Gb in one flowcell at issue #52.
What's your setup for max_chunks number and basecalling model (fast or hac)?
Do you prepare the fresh library for each loading?
How many mass of input DNA for library preparation in your experiments?

Hoping that this will not cause you too much trouble.
Thanks.

Amber

**Comment by mattloose** [comment]
HI Amber,

DNA was extracted using Qiagen PureGene. Basecalling is done with HAC. The max-chunks is 12 (see below for the relevant chunk of the toml). 

We prepare fresh library for a run, but not for each loading - i.e we just use the library we haven't loaded from the start of the run. We are loading around 600ng on each loading and we reload once every 24 hours. 

The flow cell would have started with 1600-1700 pores.

Flushing is done on the GridION - i.e we pause the run and flush with the flowcell in situ.

Hope this helps,

Best

Matt

[conditions.0]
name = "CancerPanelRepeat"
targets = "/home/grid/Documents/20200518_NB4_repeat/CancerPanelTargets.txt"
min_chunks = 0
max_chunks = 12
control = false
multi_off = "unblock"
multi_on = "stop_receiving"
single_on = "stop_receiving"
single_off = "unblock"
no_map = "proceed"
no_seq = "proceed"

**Comment by HJTsai** [comment]
Hi Matt,

It is very helpful.
ONT suggests that use 1000~1500 ng input DNA for library preparation, but about 30% DNA will be lost during library preparation procedure.
To attain 3 times loading, do you prepare 2~3 copies library for each run or just enhance the mass of input DNA at the beginning of library preparation in one copy? 

Thanks.

Amber
