### ISSUE TITLE
Applying to direct RNA seqeuencing

### ISSUE THREAD

**Issue by awjga** [LooseLab/readfish#57]
Hi,

I was wondering what do I need to change to allow this program to work on direct RNA sequencing?

Fortunately, I have kept a bulk file from one of my direct RNA sequencing runs and  I will be able to test on that.

**Comment by shka** [comment]
I posted the instruction to Community, please check.

**Comment by DrOllyGomez** [comment]
Hi to All.
I came here with the same question, but I cant tell if the changes implemented above address it: can this program now work with direct RNA sequencing data now those changes have been made?
In the comment 'I posted the instruction to Community, please check.' does the 'Community' refer to the ONT nanoporetech Community?  Or does it refer to some other Community? I would like to follow this link.
Many thanks

**Comment by DrOllyGomez** [comment]
Ah - I found it
https://community.nanoporetech.com/posts/looselab-s-readuntil-for-d

**Comment by Huanle** [comment]
Is it necessary to change the minimap2 reads mapping commands if using a genome reference? 
If so, how to make the change?
