### ISSUE TITLE
Compatibility with MinKNOW-Core 4.04

### ISSUE THREAD

**Issue by LynnLy** [LooseLab/readfish#60]
Hi there, it looks like the GridION software and MinKNOW have received major updates on July 7 (notably, python2 -> python3). The nanoporetech read_until_api has also been updated. 

Are there any plans to update ru and read_until_api_v2 to be compatible with the new MinKNOW? Thanks!

**Comment by alexomics** [comment]
Yes, we will be updating `ru` to be compatible with the latest minknow core. `read_until_api_v2` is a divergent fork of the [`nanoporetech/read_until_api`](https://github.com/nanoporetech/read_until_api), originally for python3 compatibility. As the `read_until_api` is now using python3 we will most likely use the nanoporetech one.
