### ISSUE TITLE
API may not take case-sensitive storage path names into account

### ISSUE THREAD

**Issue by ps-account** [LooseLab/readfish#61]
Hi,

Our reads usually end up in /var/lib/MinKNOW/data/ , but we noticed that with read_until activated they end up in /var/lib/minknow/data/ . Did anyone else encounter this behavior?

**Comment by alexomics** [comment]
What is the version of minknow-core you are using?

**Comment by rdwrt** [comment]
I think 3.6.5
$ cat /opt/ont/minknow/conf/MinKNOW_uid
3.6.5

**Comment by alexomics** [comment]
We don't modify the data directory that we get from the minknow api. It seems that this is an issue with that path. I will check with ONT.
