### ISSUE TITLE
0 pores and no reads in simulation

### ISSUE THREAD

**Issue by billytcl** [LooseLab/readfish#65]
I'm trying to run a simulation of the sample fast5 file and my own fast5 file using MinKNOW 20.06 and Guppy 4+.

I edited the sequencing_MIN106_DNA toml file, reset the device and plugged in the flow cell. When I tried to start the sequencing run as in step 6-7, it does a MUX scan but finds zero pores. Afterward when I let it sit, no reads are displayed. Is this an issue with the new MinKNOW? I'm not exactly sure what the issue is here.

**Comment by mattloose** [comment]
Is your fast5 file a read fast5 file or a BULK fast5 file - I suspect you are using a read fast5 file?

**Comment by 2387882242** [comment]
Hi,

I have the same problem. Can't read fast5 file be used for testing? And how do I get a BULK fast5 file?

Looking forward to your reply, thank you very much.

**Comment by alexomics** [comment]
We provide a bulk FAST5 file for download [here](http://s3.amazonaws.com/nanopore-human-wgs/bulkfile/PLSP57501_20170308_FNFAF14035_MN16458_sequencing_run_NOTT_Hum_wh1rs2_60428.fast5). Read FAST5 files cannot be used for playback.

**Comment by 2387882242** [comment]
Thank you for your comments.

I've done the playback test with the fast5 file you gave, and now I want to use my own fast5 file for a test. Is this achievable? If there's any way to convert the read fast5 file into a bulk fast5 file?
