### ISSUE TITLE
Where to look for the device id？

### ISSUE THREAD

**Issue by 12032345** [LooseLab/readfish#69]
Hello everyone,

When I am trying to run
"readfish unblock-all --device <device id> --experiment-name "Testing ReadFish Unblock All""

Results appear “raise ValueError ("Could not find device {! r}"...
 
I have no idea what device id is so I'd like to ask you where to find device id.

Thanks!

**Comment by mattloose** [comment]
Hi,

So the device ID depends on the platform you are using. If you are on a MinION then it is the MinION ID (e.g MN17171). If you are on a GridION it is the device position -   e.g. X1, X2, X3,X4 or X5.

If you are on a PromethION then don't use read until as it is currently unsupported!

Assuming you are on a MinION your command should be:

`readfish unblock-all --device MN***** --experiment-name "Testing ReadFish Unblock All"`

where you replace MN***** with your device ID.

Hope this helps.

**Comment by 12032345** [comment]
It really helps, thank you very much.
