### ISSUE TITLE
Reads number remains constant.

### ISSUE THREAD

**Issue by 12032345** [LooseLab/readfish#71]
Hi,

I am using Ubuntu 16. The latest version of MinKNOW and Guppy 4.
I am using the bulk fast5 you give for simulation.

When the mux scan begins in GridION,
Guppy server running and MinKNOW is sequencing in the background.

At first it was normal, but as run time progressed, the reads number remained constant around 500, and the estimated read length is much smaller than yours.

I don't know why, I hope to get your help.
Thank you so much.

**Comment by 12032345** [comment]
By the way, the system messages show that Disk too low to continue (Disk has 20GB space remaining). But infact, I set the output location to a disk that has 2T space. So how to clean up disk space to run such a large fast5 file？

And I did not turn on the Bulk file button，iis it its effect?

**Comment by mattloose** [comment]
OK - so the way MinKNOW works it needs some space on the main system drive even if you have set the output location to elsewhere.

So your run froze at 500 reads because the run had been stopped. 

To run more testing you are going to need more space on your system drive.
