### ISSUE TITLE
Big(ger) sizes of unblocked reads

### ISSUE THREAD

**Issue by timmocking** [LooseLab/readfish#72]
I've recently performed my first real live run where I selected for 1 chromosome as a test. Already during the run I could see a peak at 500 bp, a peak at ~4 kb with a very long tail of long reads. After this run I split up my fastq files using unblocked_reads.txt into a fastq of accepted and rejected reads. I plotted out the read lengths, as shown here:

![rejected](https://user-images.githubusercontent.com/39952912/93304496-687c8900-f7fd-11ea-9b18-8e25ca253302.png)
![accepted](https://user-images.githubusercontent.com/39952912/93304504-69adb600-f7fd-11ea-9f57-5801f4dc8028.png)

I don't worry too much about the relatively high <1kb peak for accepted reads, as we kept our run going for way too long, most likely piling up large amount of lower quality on-target short reads. 

I do wonder about the relatively high amount of reads > 1kb for the rejected ones. Our mapping speeds are consistently below 0.1s throughout the experiment with `max_chunks=4 `and `break_reads_after_seconds=0.4`. Are there solutions and/or settings I can tweak to lower the time spent on off-target reads?

I'm using readfish 0.0.5a3 with guppy 3.4.5 on a local basecall server.

**Comment by mattloose** [comment]
Can you confirm what platform you are using - is this GridION or are you using your own GPU set up?

If you are using max_chunks 4 and break_reads_after_seconds=0.4 the theoretical maximum read length for an unblocked read is around the 1kb mark (allowing for various lags in processing). I suspect that the longer reads come from issues around unblocking and messages being sent.

Were you collecting a chunk log during this run? This would allow some additional benchmarking on what is happening.

Anyway - if you can confirm the hardware platform I can offer some more comments and suggestions that may help.

**Comment by timmocking** [comment]
I'm using the GridION for everyting. What do you mean by chunk log and/or where can I find this?

**Comment by mattloose** [comment]
So you can write a chunk-log to disk using the logging options in readfish (--chunk-log).


I'm just looking at a run we have on at the moment and comparing the count and number of sequenced reads:
![image](https://user-images.githubusercontent.com/8202484/93518774-32d2bf80-f925-11ea-92a3-a9d144b8319b.png)
with unblocked reads:
![image](https://user-images.githubusercontent.com/8202484/93518842-50078e00-f925-11ea-9377-0a65612046bd.png)

We're not seeing the distribution of unblocked reads that you are.

Could you confirm what version of readfish you are running please?

Thanks,

Matt

**Comment by timmocking** [comment]
First of all I want to thank you for all the quick & helpful responses, we're really seeing some nice results overall with readfish and I appreciate how fast you all respond to my questions in the past. 

I'm using readfish 0.0.5a3 with guppy 3.4.5 (local basecall server) with MinKNOW 4.0.16. 

Here is some additional data for a run we did overnight for selection of chrom1. 

Here is a plot from the response times from the .log file. These are consistently fast for all our experiments. We are still using the fast basecaller, as the high-accuracy model does not perform fast enough.
![response_time](https://user-images.githubusercontent.com/39952912/93571535-e32bdc80-f994-11ea-8f13-af1213c3b1fd.png)

I looked in to the sequencing summary file by NanoPore where I selected for the end_reasons. Here are the value counts for all of Nanopore's "end reasons":
```
unblock_mux_change    360442
signal_negative       118493
signal_positive        60629
mux_change                 9
```

When I select for the events of unblock_mux_change and plot out the sequencing duration, I find the same pattern as I found when evaluating read lengths: one peak <1kb and another in the 3-5kb region. 
![sequencing_duration](https://user-images.githubusercontent.com/39952912/93572519-3e120380-f996-11ea-9917-cf2e247ae227.png)

This is leading me to believe that there is something wrong in the communication of the unblock signal, as we are apparently rejecting reads of considerable length. I also have  ``max_chunks=4`` and ``break_reads_after_seconds=0.4`` so I would not expect to map something after 1.6s in the first place.

I haven't generated a --chunk-log file yet for any of the runs. I could not find it in the documentation of the --help function of readfish itself. I will generate this in the future.

**Comment by mattloose** [comment]
Ahha!

Please try with these additional options set in your readfish command:

`--action-throttle 0.4 --throttle 0.4`

We're playing a little with these parameters and we think this will help you!

Best wishes

Matt

**Comment by mattloose** [comment]
Oh - and you need to do:

`readfish targets --help`

We will enhance the log description though - it's a debug log that we use a fair bit.

**Comment by timmocking** [comment]
We just set up a new run with `--action-throttle 0.4 --throttle 0.4` and could immediately tell that it's working now as intended! Just a very sharp peak at ~500 bp. Really excited to look at these new results. Thanks! 👍

**Comment by mattloose** [comment]
Great that it's improved things for you! 

If I am correct you are on a mk1 GridION? If so we may have an additional fix next week that will allow you to use HAC again.
