### ISSUE TITLE
Ont-pyguppy-client-lib's version issue.

### ISSUE THREAD

**Issue by 12032345** [LooseLab/readfish#73]
Hey，

I am using Ubuntu 16. The latest version of MinKNOW and Guppy 4. I'm using GridION to install readfish.

I've successfully installed readfish before, but then I restarted GridION, maybe GridION made some updates automatically, and it appeared a error like this: could not find a version that satisfies the requirement ont-pyguppy-client-lib==4.0.11(from pyguppyclient>=0.0.7a1->readfish)(from versions: )

Has anyone ever had a similar problem? How did you solve it?

**Comment by mattloose** [comment]
Can you confirm which version of readfish you are trying to install  please?

**Comment by 12032345** [comment]
Thank you very much for your reply.

The version I'm trying to install is readfish==0.0.5a2.

**Comment by mattloose** [comment]
OK - just asking @alexomics to comment on this when he has a moment.

**Comment by joanmarticarreras** [comment]
Just for the record, I experience the exact same problem on a freshly installed Ubuntu 18.04 and same guppy and MinKNOW versions.

Additionally, with the recent MinKNOW GUI, it's not apparent when should we try to load the scripts (or simulation to test the software), did you do some adaptations? Do you know from where can we snatch older versions of MinKNOW that are compatible with script loading?

Joan

**Comment by mattloose** [comment]
Can we check what python version you are using? The current code - for reasons beyond our control - is only python 3.7 compatible. In the future this should change.

To reload scripts you need to look for the three dots in the right hand corner of the interface when you are starting a run. Click on that and you will see reload scripts.

**Comment by fbrennen** [comment]
It would also be worth checking what pip version you're using -- `ont-pyguppy-client-lib` wheels are built to the `manylinux2010` standard, and that requires pip >= 19.0.

**Comment by mattloose** [comment]
Thanks Forrest -that is indeed worth checking! Didn't think of that....

pip install pip --upgrade
