### ISSUE TITLE
Logging message about target regions

### ISSUE THREAD

**Issue by timmocking** [LooseLab/readfish#74]
I'm trying to target hundreds of genetic regions spread across all chromosomes. I have all of these regions added to the "targets" variable in the toml file as follows:

targets = ["chr1,start,end,+",
"chr1,start,end,-",
"chr3,start,start,+",
"chr5,start,end,-",
"chr7,start,end,+",

Using the + and - to target both sense and anti-sense reads for the same regions. However, when I start my run I get the following message:

`Region 'XXX' (control=False) has 22 targets of which 22 are in the reference. Reads will be unblocked when classed as single_off or multi_off; sequenced when classed as single_on or multi_on; and polled for more data when classed as no_map or no_seq.
`

Do "targets" here refer to the contigs on which I define these regions (that is, they are spread across 22 contigs which are present in my reference) or is there something going wrong? Since technically I added hundreds of targets I would expect something like ``Region 'XXX' (control=False) has 600 targets of which 600 are in the reference. ``

**Comment by alexomics** [comment]
Yes, here targets refers to the contigs, we don't currently check that all regions are within the bounds of a contig. This is a holdover from when we only accepted entire contigs as targets.

**Comment by mattloose** [comment]
Certainly something we should consider doing @alexomics  - noted you've added it as an enhancement!

**Comment by Adoni5** [comment]
Closed as fixed in `2023.1.1`
