### ISSUE TITLE
Simultaneous on + off-target mapping

### ISSUE THREAD

**Issue by timmocking** [LooseLab/readfish#75]
In the case of the following TOML settings:

```
single_on = "stop_receiving"  
multi_on = "stop_receiving"  
single_off = "unblock"  
multi_off = "unblock"
```

What happens if a read has both an on-target AND off-target mapping? Does single_on overrule single_off or the other way around?

**Comment by mattloose** [comment]
this would be described as a mulit_on case - so it has multiple mapping targets at least one of which is in your target list. multi_off is multiple mappings of which none are in your target list.
