### ISSUE TITLE
How to find minimap2 index of the human genome?

### ISSUE THREAD

**Issue by 12032345** [LooseLab/readfish#76]
I haven't used minimap2 before. Not familiar with it yet.

So how do I find the minimap2 index of the human genome after I install minimap2?

**Comment by mattloose** [comment]
Hi

You need to follow the instructions provided for minimap2 here - [https://github.com/lh3/minimap2](https://github.com/lh3/minimap2)

In brief, download a copy of the human reference and then build a minimap2 index using the -d flag.

**Comment by 12032345** [comment]
Hi，


Thanks for your reply.


I downloaded the human genome data from NCBI: GCF_000001405.39_GRCh38.p13/GCF_000001405.39_GRCh38.p13_genomic.fna.gz.&nbsp;
And then I build a minimap2 index using the -d flag.&nbsp;


But the experiment report tell me that the targets are not represented in the reference: Region 'select_chr_21_22' (control=False) has 2 targets of which 0 are in the reference.&nbsp;
Is this a chromosome name error? Is there something wrong with the data I downloaded?


I'm sorry to bother you, but I'd love to hear from you.



&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------

**Comment by mattloose** [comment]
Correct. It’s a chromosome name error.
You need to make sure the chromosome names are the same in the toml as in the reference. 

So change the chr21 and chr22 in the toml to however the chromosomes are named in your reference and test again.
