### ISSUE TITLE
Unblocking results in longer reads than expected and readfish targets perfomance issue

### ISSUE THREAD

**Issue by utrori** [LooseLab/readfish#79]
Hello.
I am facing two issues and hope to get help.
First, when I perform unblock-all, it surely changes the size distribution to shorter side, but they are much longer than the expected results shown in the example. I attach the size distribution after unblocking for about 20 min.

![Screenshot from 2020-09-24 16-06-15_2](https://user-images.githubusercontent.com/5716037/94119029-4633dc80-fe89-11ea-8ece-347eda6a41f5.jpg)

I also attach some logs.

**INFO 2020-09-24 16:30:24,980 ru.unblock_all Took 0.013920 for 33 reads
2020-09-24 16:30:24,980 ru.unblock_all Took 0.013920 for 33 reads
INFO 2020-09-24 16:30:25,068 ru.unblock_all Took 0.001787 for 4 reads
2020-09-24 16:30:25,068 ru.unblock_all Took 0.001787 for 4 reads
INFO 2020-09-24 16:30:25,177 ru.unblock_all Took 0.009880 for 24 reads
2020-09-24 16:30:25,177 ru.unblock_all Took 0.009880 for 24 reads
INFO 2020-09-24 16:30:25,281 ru.unblock_all Took 0.013355 for 27 reads
2020-09-24 16:30:25,281 ru.unblock_all Took 0.013355 for 27 reads
INFO 2020-09-24 16:30:25,393 ru.unblock_all Took 0.024499 for 42 reads
2020-09-24 16:30:25,393 ru.unblock_all Took 0.024499 for 42 reads
INFO 2020-09-24 16:30:25,481 ru.unblock_all Took 0.012475 for 30 reads
2020-09-24 16:30:25,481 ru.unblock_all Took 0.012475 for 30 reads**

The second issue is that I when I perform readfish targets, the times shown are much longer than 0.4 sec.
The toml file I used got validated.

[hum_chr_selection.toml.txt](https://github.com/LooseLab/readfish/files/5274477/hum_chr_selection.toml.txt)
[ru_test.log](https://github.com/LooseLab/readfish/files/5274469/ru_test.log)

My environment:
Ubuntu 18.04
python: 3.7.0
CPU: ryzen5 2400g
GPU: GTX1080
MinKNOW: 4.0.4
Guppy: 4.0.15
Readfish: 0.0.5a2

**Comment by mattloose** [comment]
Hi,

For your unblock command please add the following flags:

--action-throttle 0.4 --throttle 0.4

This should also be used for readfish targets.

Please also switch from the HAC model to FAST in your toml file.

Finally please switch the max chunks flag from "inf" to 12.

We have another tweak coming shortly that will help improve all this further,

Matt

**Comment by utrori** [comment]
Hi Matt,

Thank you for your quick and on-point response!
Both the issues are now resolved!
