### ISSUE TITLE
Whether readfish 0.0.5a2 implements in MinKNOW (minknow-core v4.0.5) 23/09/2020 released form ONT?

### ISSUE THREAD

**Issue by HJTsai** [LooseLab/readfish#80]
Hi,

For readfish 0.0.5a2, you mentioned that this toolkit currently requires MinKNOW (minknow-core v4.0.4) and Guppy (>=v4.0.11) to be installed.
Whether this toolkit implements in MinKNOW (minknow-core v4.0.5) 23/09/2020 released form ONT?

Amber

**Comment by mattloose** [comment]
Hi Amber,

Yes - the version should be compatible. I would definitely run a playback test though.

Matt

**Comment by HJTsai** [comment]
Hi Matt, 

Thanks for your reply.

Amber
