### ISSUE TITLE
Non-human reference genome and host depletion?

### ISSUE THREAD

**Issue by lindsrowd** [LooseLab/readfish#95]
Hello, 

I am wanting to use a non-human reference genome (not annotated to chromosome level) and sequence reads that do not match the reference.  What would be the best way to request this in the TOML file? And what would I put as the target values?

Thanks in advance, 

Lindsey

**Comment by mattloose** [comment]
Hi Lindsey,

A good question!

Assuming your reference contains sequences labelled:
```
>contig000001
ATGATGATGTA
>contig000002
ATGTAGTAGTGA
```
etc.
You should add the sequence names as the targets:
```
targets = [‘contig000001’,‘contig000002’]
```
If I understand correctly, you only want to sequence reads that do not come from your reference - so you want to do host rejection?
In that case you should set:
```
min_chunks = 0
max_chunks = inf
targets = [‘contig000001’,‘contig000002’]
single_on = “unblock”
multi_on = “unblock”
single_off = “stop_receiving”
multi_off = “stop_receiving”
no_seq = “proceed”
no_map = “proceed”
```

However - there is another way of doing the same thing:
```
min_chunks = 12
max_chunks = inf
targets = [‘contig000001’,‘contig000002’]
single_on = “stop_receiving”
multi_on = “stop_receiving”
single_off = “stop_receiving”
multi_off = “stop_receiving”
no_seq = “proceed”
no_map = “proceed”
```
This will behave a little differently. By definition it will unblock *anything* that maps to the reference within the fist 12 times it sees the read. After that it will ignore the molecule and allow it to finish sequencing. This setting is experimental but may give you better flowcell life. Specifically it will prevent our code from trying to unblock long molecules - which may lead to them tangling.

I would suggest testing this by running against a bulkfile and deliberately omitting something you know should sequence.

I hope that helps.
