### ISSUE TITLE
Unblocking not working? and low depth at targets

### ISSUE THREAD

**Issue by Tine-dk** [LooseLab/readfish#97]
Hi, 

I have run ReadFish on a sample (72 hours) but it seems like the unblocking does not work, as I have some long reads at the targets but very close small reads everywhere else. There are even some longer reads off-target. 
I'm using the "fast" basecalling and not HAC, could that be the problem?

The images below are centered around HTT, SBMA, and off target.
![image](https://user-images.githubusercontent.com/67691621/96088311-86551080-0ec5-11eb-9768-f36dcb57ae6b.png)
![image](https://user-images.githubusercontent.com/67691621/96088332-8e14b500-0ec5-11eb-9bd1-aa51e831bfaf.png)
![image](https://user-images.githubusercontent.com/67691621/96088404-adabdd80-0ec5-11eb-9aed-cf82449b3af9.png)

Chromosome 2 and 7 contain no targets, but their mean is not lower than chromosomes containing targets.
The ReadFish summary:
![image](https://user-images.githubusercontent.com/67691621/96110505-3d5e8580-0ee0-11eb-9f5d-04f43d7b0b99.png)

Does it look right or are there some settings I might have misunderstood? 
The simulation looked like the last image, but without long reads.
Also, is there any way to increase the read-depth? I hoped for a greater number of long reads at the target sites. 

The targets are given like so:
`chr, start-50.000,end+1.000,+
chr, start-1.000,end+50.000,-

Example:
4,3026604,3077670,+
4,3075604,3126770,-`

break_reads_after_seconds are set to 0.4, and the run was not done with the simulation toml.

My ru_generators file looks like this:
`#!/miniconda3/envs/readfish_guppy3/bin/python ` 
![image](https://user-images.githubusercontent.com/67691621/96095846-780bf200-0ecf-11eb-849f-fe3655253d76.png)
Where am I supposed to set control=false in the ru_generators (Gatcha #4)?

Thanks for helping :D

**Comment by mattloose** [comment]
It looks to us like your total yield on the run was around 11.5Gb. This would be approximately 4x over a human genome. What you are seeing here is an increase in coverage on your targets with long reads, leading to (from your IGV plots) an increase in coverage.

So - we think - based on what you are showing - that targeting is working and reads are being unblocked when off target and sequenced when on target. Why it is not efficient is interesting. Did you flush and reload your library at any point? Can you share the pass fail read count plots? Or even a MinKNOW report for this run?

And most importantly how big is your total target space relative to the size of the genome?

**Comment by Tine-dk** [comment]
Hi, it sounds great that you think the targeting and unblocking is working.

I did flush and reload library after 24H. Though the occupancy of the pores was only ~50% due to a lower sample concentration.

The target size is (~102000*27)/3101788170 = 0.0008878749, so maybe we should increase the target areas?


I'm not sure there are pass fail count plots, as there somehow are no pass/fail fast5 folders. 

I'm not sure which report you are seeking but I attached some. 
[final_summary_FAL84901_820b847d.txt](https://github.com/LooseLab/readfish/files/5385411/final_summary_FAL84901_820b847d.txt)

[final_summary_FAL84901_820b847d_subset.txt](https://github.com/LooseLab/readfish/files/5385557/final_summary_FAL84901_820b847d_subset.txt)

**Comment by mattloose** [comment]
Can you share the run report PDF file? It will be report_*.pdf 

We expect the occupancy to be lower during a read fish run but it sounds as though your occupancy is low.

But it sounds like something else has gone wrong here. Which MinKNOW version are you on? And which guppy version?

Your target region is a very small fraction of the genome - we haven't gone this low but I would anticipate higher enrichment.

I've pasted a duty time plot for a run we did a while back - how does the occupancy of the pores compare here with yours?

![image](https://user-images.githubusercontent.com/8202484/96158089-09e52080-0f0b-11eb-977d-bd6f52558cd0.png)

**Comment by Tine-dk** [comment]
Hi, :) 
Unfortunately, I only have a "report_.md" and not a pdf.  I don't know why there is no "report_.pdf". 
I'm using ReadFish 0.0.5a3 and Guppy 3.4.5. 
MinKNOW version is 20.06.4 with GUI version 4.0.20.

The Duty Time Plot looks like this:
![image](https://user-images.githubusercontent.com/67691621/96235151-b7534500-0f9a-11eb-9d2a-e6f0e1312dd0.png)


Is it normal that there are many short reads in the target region? 
Also, have you experienced an improvement in an experiment by using the HAC basecaller instead of the fast one? I'm wondering if it could make a difference for the target regions, such that some of the "short reads" might become sequenced for longer.

**Comment by mattloose** [comment]
Hi,

OK - so the short reads in the target regions depends on a lot of factors - in particular the nature of the library and how it runs without adaptive sampling. Can you share your toml file so we can check the actions with multiple targets reported etc?

Your duty time plot suggests that this library is underloaded. How much material did you load onto the flowcell at the start of the run? You will find better enrichment by overloading the flowcell to keep occupancy up.

Your run should be generating a PDF report at the end in the same location as the report_*.md file. You might want to talk about that with ONT.

Best 

Matt

**Comment by Tine-dk** [comment]
Hi,

I loaded ~700 ng (24 fmol) first time and after washing I loaded ~500 ng (18 fmol). I will try and load more in my next run, thanks. :) By overloading do you mean loading more than 50 fmol? 

Do you have eny tips and tricks to get less short reads in the target areas?

I figured out to create a pdf report:
[targets.txt](https://github.com/LooseLab/readfish/files/5391513/targets.txt)
[4fe98fbd-19f1-4418-8907-7020f3403b60.pdf](https://github.com/LooseLab/readfish/files/5391510/4fe98fbd-19f1-4418-8907-7020f3403b60.pdf)

**Comment by mattloose** [comment]
How long are you expecting your molecules to be?

**Comment by Tine-dk** [comment]
At the Tapestation I got peaks at 203, 395, 1418 and >60.000 bp. 
The greatest peak was at >60.000 and the shorter length had lower peaks.

**Comment by mattloose** [comment]
OK - this is a tricky one.

At 24 fmol your library is underloaded. BUT it looks like you are going for really quite long reads.

If you want higher coverage I would consider shearing your DNA to a mean read length in the 10-15 kb range. This may improve things for you.

But you should defintiely load as much as you can to ensure good occupancy on the flowcell.

Hope this helps.
