### ISSUE TITLE
Host depletion

### ISSUE THREAD

**Issue by 12032345** [LooseLab/readfish#99]
Hi,

I have tested readfish and it seems to work well.

Now I want to do a host depletion test with my own Fast5 file. I want to enrich archaea from bactieria host. Should I use the entire bacterial genome as a reference？ And How do I use so many references to do host depletion?

Looking forward to your reply.

**Comment by mattloose** [comment]
Hi,

Is this a specific bacterial host or all bacteria?

Is it a specific archaea or any archaea?

Thanks,

Matt

**Comment by 12032345** [comment]
Hi Matt,

Thanks for your kind reply. The thing is, I have an fast5 file for an environmental sample that contains sequences of various bacteria and achaea. Now I want to do a test to enrich archaea and deplete bacteria. And I've used all achaea sequences as reference.

But I'm having a new problem，I noticed that read fast5 file can't do a playback test. So how can I do the test? Maybe I should convert the read fast5 file into a bulk fast5 file？And how？

Hope to get your help.

Sincerely,
sophie

**Comment by mattloose** [comment]
Hi Sophie,

Unfortunately you can't make a bulk fast5 file from read fast5 files.

But you don't need to test your exact problem. You can use the bulkfile we have provided to test that your setup works properly. Then you can make sure your system performs well enough to think about your actual experiment.

Your actual experiment is more difficult though. You can only unblock things that you know are in the sample unless you use our centrifuge pipeline. But this would require some further modifications to do what you want.

You can try providing a file with all the common bacteria you might want to deplete and use that. 

The only way to test your experiment on your data will be to save a bulkfile whilst you are sequencing. If you look on the nanopore website they explain how to do that.

Hope this helps.

**Comment by 12032345** [comment]
Hi Matt,

I saved my own bulk file when I sequencing with flongle, and the file name is something like "ACL415_2d19df4d_0.fast5".
The playback with your bulk fast5 was OK, but I get a "Script failed. Please check for error messages below or restart the experiment. If the problem persists please contact Support" error when I use my own bulk file for a playback experiment.

Where's the problem? I hope I can get your advice. Thanks in advance!

Sincerely,
sophie

**Comment by 12032345** [comment]
Hi Matt,

I have saved my bulk fast5 file for an environmental sample that contains sequences of various bacteria and achaea（3.5%）. And I did a playback test to enrich archaea.  I've used all achaea sequences as reference as well as target, and my TOML was:

[caller_settings]
config_name = "dna_r9.4.1_450bps_fast"
host = "127.0.0.1"
port = 5555

[conditions]
reference = "/home/grid/software/minimap2/archaea_ref.mmi"

[conditions.0]
name = "archaea_enrich"
control = false
min_chunks = 0
max_chunks = inf
targets = "/home/grid/software/archaea_target"
single_on = "stop_receiving"
multi_on = "stop_receiving"
single_off = "unblock"
multi_off = "unblock"
no_seq = "proceed"

no_map = "proceed"

But in the system messages, it was always unblocked 0 reads. Enrich archaea didn't seem to be playing its part.
My readfish version is 0.0.5a4, and here are log files:
![image](https://user-images.githubusercontent.com/70840449/100212393-39df0500-2f48-11eb-8e37-6fc4922ef1c0.png)
What went wrong? 
Any suggestions will be appreciated. Looking forward to your reply！

Sincerely,
sophie

**Comment by 12032345** [comment]
Hi matt，

Thank you for your meaningful work and kind reply！

I want to try your centrifuge pipeline to deplete bacteria in my environmental samples which contain a variety of bacteria and archaea. Could you tell me some details about how the centrifuge pipeline is used?

Looking forward to your reply.

Sincerely,
sophie
